import { Product } from './types'

const rawProducts: Product[] = [
  {
    id: '1',
    name: 'Skjorta',
    description: 'Elegant herrskjorta',
    price: 599,
    category: 'Men',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Vit', 'Blå', 'Svart'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '2',
    name: 'Klänning',
    description: 'Somrig damklänning',
    price: 799,
    category: 'Women',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Röd', 'Blå', 'Grön'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '3',
    name: 'T-shirt',
    description: 'Färgglad barn t-shirt',
    price: 199,
    category: 'Children',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Gul', 'Orange', 'Turkos'],
    sizes: ['2-3år', '4-5år', '6-7år', '8-9år'],
  },
  {
    id: '4',
    name: 'Sneakers',
    description: 'Bekväma sportskor',
    price: 899,
    category: 'Shoes',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Svart', 'Vit', 'Grå'],
    sizes: ['36', '37', '38', '39', '40'],
  },
  {
    id: '5',
    name: 'Solglasögon',
    description: 'Stilrena solglasögon',
    price: 399,
    category: 'Accessories',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Svart', 'Brun', 'Röd'],
  },
  {
    id: '6',
    name: 'Handväska',
    description: 'Läderväska',
    price: 1299,
    category: 'Bags',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Svart', 'Brun', 'Beige'],
  },
  {
    id: '7',
    name: 'Halsband',
    description: 'Silversmycke',
    price: 499,
    category: 'Jewelry',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Silver', 'Guld', 'Röd'],
  },
  {
    id: '8',
    name: 'Yogamatta',
    description: 'Halkfri träningsmatta',
    price: 349,
    category: 'Sports & Leisure',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Grön', 'Blå', 'Svart'],
  },
  {
    id: '9',
    name: 'Kudde',
    description: 'Dekorativ prydnadskudde',
    price: 249,
    category: 'Home & Decor',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Vit', 'Grå', 'Beige'],
  },
  {
    id: '10',
    name: 'Hörlurar',
    description: 'Trådlösa hörlurar',
    price: 1499,
    category: 'Electronics',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Svart', 'Vit', 'Grå'],
  },
  {
    id: '11',
    name: 'Ansiktskräm',
    description: 'Fuktgivande dagkräm',
    price: 299,
    category: 'Beauty & Health',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Vit', 'Grön', 'Blå'],
  },
  {
    id: '12',
    name: 'Boxershorts',
    description: 'Bekväma underkläder',
    price: 149,
    category: 'Underwear',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Vit', 'Grå', 'Svart'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '13',
    name: 'Vinterjacka',
    description: 'Varm dunjacka',
    price: 1999,
    category: 'Outerwear',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Svart', 'Blå', 'Grön'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '14',
    name: 'Bikini',
    description: 'Somrig badkläder',
    price: 399,
    category: 'Swimwear',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Röd', 'Blå', 'Grön'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '15',
    name: 'Trendiga jeans',
    description: 'Nyhet för säsongen',
    price: 699,
    category: 'New Arrivals',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Blå', 'Svart', 'Ljusblå'],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: '16',
    name: 'Stickad tröja',
    description: 'Reapris!',
    price: 299,
    category: 'Sale',
    inStock: true,
    image: '/hero-image.png',
    colors: ['Grå', 'Beige', 'Vinröd'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '17',
    name: 'Keps',
    description: 'Baseballkeps med logga',
    price: 199,
    category: 'Accessories',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '18',
    name: 'Väska',
    description: 'Ryggsäck för skola',
    price: 499,
    category: 'Bags',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '19',
    name: 'Örhängen',
    description: 'Guldpläterade örhängen',
    price: 299,
    category: 'Jewelry',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '20',
    name: 'Hantlar',
    description: 'Justerbara träningshantlar',
    price: 799,
    category: 'Sports & Leisure',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '21',
    name: 'Lampför',
    description: 'Modern golvlampa',
    price: 899,
    category: 'Home & Decor',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '22',
    name: 'Högtalare',
    description: 'Bluetooth-högtalare',
    price: 699,
    category: 'Electronics',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '23',
    name: 'Schampo',
    description: 'Näringsrikt hårschampo',
    price: 149,
    category: 'Beauty & Health',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '24',
    name: 'Strumpbyxor',
    description: 'Genomskinliga strumpbyxor',
    price: 99,
    category: 'Underwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '25',
    name: 'Regnjacka',
    description: 'Vattentät regnjacka',
    price: 599,
    category: 'Outerwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '26',
    name: 'Badbyxor',
    description: 'Herrbadbyxor',
    price: 249,
    category: 'Swimwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '27',
    name: 'T-shirt',
    description: 'Limited edition t-shirt',
    price: 399,
    category: 'New Arrivals',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '28',
    name: 'Jeans',
    description: '50% rabatt!',
    price: 349,
    category: 'Sale',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '29',
    name: 'Blazer',
    description: 'Klassisk herrblazer',
    price: 1299,
    category: 'Men',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '30',
    name: 'Kjol',
    description: 'Elegant damkjol',
    price: 699,
    category: 'Women',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '31',
    name: 'Overall',
    description: 'Barnoverall',
    price: 399,
    category: 'Children',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '32',
    name: 'Sandaler',
    description: 'Sommersandaler',
    price: 499,
    category: 'Shoes',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '33',
    name: 'Armbandsur',
    description: 'Elegant herrklocka',
    price: 1999,
    category: 'Accessories',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '34',
    name: 'Plånbok',
    description: 'Läderplånbok',
    price: 399,
    category: 'Bags',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '35',
    name: 'Ring',
    description: 'Silverring med sten',
    price: 599,
    category: 'Jewelry',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '36',
    name: 'Yogablock',
    description: 'Skumblock för yoga',
    price: 199,
    category: 'Sports & Leisure',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '37',
    name: 'Väggspegel',
    description: 'Rund dekorativ spegel',
    price: 799,
    category: 'Home & Decor',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '38',
    name: 'Laddare',
    description: 'Snabb-laddare för mobil',
    price: 299,
    category: 'Electronics',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '39',
    name: 'Deodorant',
    description: '48-timmars skydd',
    price: 89,
    category: 'Beauty & Health',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '40',
    name: 'Trosor',
    description: 'Bambutrosor 3-pack',
    price: 199,
    category: 'Underwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '41',
    name: 'Vindjacka',
    description: 'Lätt vindtät jacka',
    price: 499,
    category: 'Outerwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '42',
    name: 'Baddräkt',
    description: 'En-delad baddräkt',
    price: 349,
    category: 'Swimwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '43',
    name: 'Hoodie',
    description: 'Ny hoodie-kollektion',
    price: 599,
    category: 'New Arrivals',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '44',
    name: 'Tröja',
    description: 'Extrapris!',
    price: 199,
    category: 'Sale',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '45',
    name: 'Byxor',
    description: 'Chinobyxor för herr',
    price: 799,
    category: 'Men',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '46',
    name: 'Blus',
    description: 'Silkesblus för dam',
    price: 899,
    category: 'Women',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '47',
    name: 'Strumpor',
    description: 'Barnstrumpor 6-pack',
    price: 149,
    category: 'Children',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '48',
    name: 'Kängor',
    description: 'Vinterkängor',
    price: 1299,
    category: 'Shoes',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '49',
    name: 'Bälte',
    description: 'Läderbälte',
    price: 299,
    category: 'Accessories',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '50',
    name: 'Portfölj',
    description: 'Affärsportfölj',
    price: 899,
    category: 'Bags',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '51',
    name: 'Öronringar',
    description: 'Små guldörhängen',
    price: 199,
    category: 'Jewelry',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '52',
    name: 'Springsko',
    description: 'Löparskor',
    price: 999,
    category: 'Sports & Leisure',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '53',
    name: 'Gardin',
    description: 'Blackout-gardin',
    price: 499,
    category: 'Home & Decor',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '54',
    name: 'Hörlursfodral',
    description: 'Skyddande fodral',
    price: 149,
    category: 'Electronics',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '55',
    name: 'Ansiktsmask',
    description: 'Guldlödermask',
    price: 199,
    category: 'Beauty & Health',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '56',
    name: 'Nattlinne',
    description: 'Silkesnattlinne',
    price: 399,
    category: 'Underwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '57',
    name: 'Fleecejacka',
    description: 'Varm fleecejacka',
    price: 699,
    category: 'Outerwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '58',
    name: 'Badmössa',
    description: 'Simmössa',
    price: 79,
    category: 'Swimwear',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '59',
    name: 'Skjorta',
    description: 'Ny färgkombination',
    price: 499,
    category: 'New Arrivals',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '60',
    name: 'Byxor',
    description: 'Sista chansen!',
    price: 299,
    category: 'Sale',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '61',
    name: 'Kostym',
    description: 'Herrkostym',
    price: 2499,
    category: 'Men',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '62',
    name: 'Klänning',
    description: 'Festklänning',
    price: 1499,
    category: 'Women',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '63',
    name: 'Overall',
    description: 'Vinteroverall barn',
    price: 799,
    category: 'Children',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '64',
    name: 'Tofflor',
    description: 'Hemmatofflor',
    price: 199,
    category: 'Shoes',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '65',
    name: 'Solhatt',
    description: 'Strawhatt',
    price: 299,
    category: 'Accessories',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '66',
    name: 'Väska',
    description: 'Crossbody-väska',
    price: 599,
    category: 'Bags',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '67',
    name: 'Armband',
    description: 'Vänskapsarmband',
    price: 99,
    category: 'Jewelry',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '68',
    name: 'Cykel',
    description: 'Mountainbike',
    price: 3999,
    category: 'Sports & Leisure',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '69',
    name: 'Matta',
    description: 'Persisk matta',
    price: 1999,
    category: 'Home & Decor',
    inStock: true,
    image: '/hero-image.png',
  },
  {
    id: '70',
    name: 'Powerbank',
    description: '20000mAh powerbank',
    price: 499,
    category: 'Electronics',
    inStock: true,
    image: '/hero-image.png',
  },
]

export const products = rawProducts