'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'sv' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, vars?: Record<string, string | number>) => string
}

const translations = {
  sv: {
    // Header & Navigation
    search: 'Sök produkter...',
    login: 'Logga in',
    logout: 'Logga ut',
    hello: 'Hej',
    cart: 'Varukorg',
    menu: 'Meny',
    categories: 'Kategorier',
    deliveryDay: '24 arbetsdagar',
    imageSearch: 'Bildsök',
    closeMenu: 'Stäng meny',
    goToMyPages: 'Gå till Mina sidor',
    loginPrompt: 'Logga in för att se dina beställningar och spara favoriter',
    searchProducts: 'Sök på BOXSHE',
    quickLinks: 'Snabblänkar',
    home: 'Hem',
    information: 'Information',
    language: 'Språk / Language',
    swedish: 'Svenska',
    english: 'English',
    
    // Products
    products: 'Våra Produkter',
    addToCart: 'Kundvagn',
    outOfStock: 'Slutsåld',
    productDetails: 'Produktdetaljer',
    specifications: 'Specifikationer',
    description: 'Beskrivning',
    price: 'Pris',
    category: 'Kategori',
    availability: 'Tillgänglighet',
    inStock: 'I lager',
    outOfStockBadge: 'Slut i lager',
    quantity: 'Antal',
    addToCartBtn: 'Lägg i varukorg',
    colors: 'Färger',
    relatedProducts: 'Liknande produkter',
    loadMore: 'Visa fler',
    
    // Cart & Checkout
    total: 'Totalt',
    emptyCart: 'Din varukorg är tom',
    continueShoppingBtn: 'Fortsätt handla',
    removeBtn: 'Ta bort',
    clearCartBtn: 'Töm varukorg',
    image: 'Bild',
    goToCart: 'Gå till varukorg',
    closeCart: 'Stäng kundvagn',
    decreaseQuantity: 'Minska antal',
    increaseQuantity: 'Öka antal',
    removeProduct: 'Ta bort produkt',
    itemsSingular: 'artikel',
    itemsPlural: 'artiklar',
    emptyCartHint: 'Utforska sortimentet – dina val visas här.',
    pricePerUnit: 'st',
    cartEmptyBody: 'Börja handla för att lägga till produkter i varukorgen.',
    cartFreeShip1: 'Handla för ',
    cartFreeShip2: ' till för ',
    cartFreeShipFree: 'fri frakt',
    cartFreeShip3: ' (gräns 120 USD).',
    cartFreeShippingOnOrder: 'Fri frakt på din beställning',
    cartNoImage: 'Ingen bild',
    cartSummaryTitle: 'Sammanfattning',
    cartSubtotal: 'Delsumma',
    cartShipping: 'Frakt',
    cartShippingFree: 'Gratis',
    cartVatIncluded: 'Inkl. moms',
    goToCheckout: 'Gå till kassa',
    cartTrustFast: 'Snabb leverans',
    cartTrustSecure: 'Säker betalning',
    cartTrustReturns: '30 dagars öppet köp',

    // Mina sidor
    myPagesTitle: 'Mina sidor',
    myPagesWelcomeBack: 'Välkommen tillbaka,',
    myPagesQuickActions: 'Snabbåtgärder',
    myPagesBackAria: 'Tillbaka till Mina sidor',
    myPagesLabelNameColon: 'Namn:',
    myPagesLabelEmailColon: 'E-post:',
    myPagesCardAccountTitle: 'Kontoinformation',
    myPagesCardAccountSubtitle: 'Hantera dina uppgifter',
    myPagesCardOrdersTitle: 'Mina beställningar',
    myPagesCardOrdersSubtitle: 'Se dina ordrar',
    myPagesCardOrdersBody: 'Visa och spåra dina beställningar',
    myPagesCardAddressesTitle: 'Adresser',
    myPagesCardAddressesSubtitle: 'Hantera leveransadresser',
    myPagesCardAddressesBody: 'Spara och redigera dina adresser',
    myPagesCardPaymentTitle: 'Betalmetoder',
    myPagesCardPaymentSubtitle: 'Hantera betalning',
    myPagesCardPaymentBody: 'Spara och hantera betalmetoder',
    myPagesCardWishlistTitle: 'Önskelista',
    myPagesCardWishlistSubtitle: 'Sparade produkter',
    myPagesCardWishlistBody: 'Se dina favoritprodukter',
    myPagesCardSettingsTitle: 'Inställningar',
    myPagesCardSettingsSubtitle: 'Kontoinställningar',
    myPagesCardSettingsBody: 'Ändra lösenord och preferenser',
    myPagesAccountPageTitle: 'Kontoinformation',
    myPagesAccountPageSubtitle: 'Hantera dina personuppgifter',
    myPagesPersonalDataTitle: 'Personuppgifter',
    myPagesPersonalDataSubtitle: 'Uppdatera din kontoinformation',
    myPagesLabelName: 'Namn',
    myPagesLabelEmailAddress: 'E-postadress',
    myPagesEdit: 'Redigera',
    myPagesSaveChanges: 'Spara ändringar',
    myPagesCancel: 'Avbryt',
    myPagesOrdersPageTitle: 'Mina beställningar',
    myPagesOrdersPageSubtitle: 'Visa och spåra dina beställningar',
    ordersLoading: 'Laddar beställningar...',
    ordersFetchError: 'Kunde inte hämta beställningar',
    ordersGenericError: 'Något gick fel vid hämtning av beställningar',
    ordersEmptyTitle: 'Inga beställningar ännu',
    ordersEmptyBody: 'Du har inte gjort några beställningar än.',
    orderNumberLabel: 'Ordernummer',
    orderDateLabel: 'Datum',
    orderQtyShort: 'Antal:',
    orderSizeShort: 'Storlek:',
    orderColorShort: 'Färg:',
    orderLineImage: 'Bild',
    orderTrackButton: 'Spåra order',
    paymentMethodCard: 'Kortbetalning',
    orderStatusConfirmed: 'Bekräftad',
    orderStatusPacking: 'Packas',
    orderStatusTransport: 'Transport',
    orderStatusDelivered: 'Levererad',
    paymentStatusPaid: 'Betald',
    paymentStatusPending: 'Väntar på betalning',
    paymentStatusFailed: 'Betalning misslyckades',
    paymentStatusRefunded: 'Återbetald',
    myPagesAddressesPageTitle: 'Adresser',
    myPagesAddressesPageSubtitle: 'Hantera dina leveransadresser',
    addressesEmptyTitle: 'Inga sparade adresser',
    addressesEmptyBody: 'Du har inte sparat några leveransadresser än.',
    addressesAdd: 'Lägg till adress',
    addressesYourTitle: 'Dina adresser',
    addressesFormTitle: 'Lägg till ny adress',
    addressesLabelStreet: 'Gatuadress',
    addressesPlaceholderStreet: 'Gatuadress',
    addressesLabelPostal: 'Postnummer',
    addressesLabelCity: 'Stad',
    addressesPlaceholderCity: 'Stad',
    addressesLabelPhone: 'Telefonnummer',
    addressesPlaceholderPhone: '070-123 45 67',
    addressesDefaultCheckbox: 'Använd som standardadress',
    addressesSave: 'Spara adress',
    addressesDefaultBadge: 'Standardadress',
    addressesSetDefault: 'Standard',
    addressesPlaceholderFullName: 'För- och efternamn',
    myPagesPaymentPageTitle: 'Betalmetoder',
    myPagesPaymentPageSubtitle: 'Hantera dina betalmetoder',
    paymentEmptyTitle: 'Inga sparade betalmetoder',
    paymentEmptyBody: 'Du har inte sparat några betalmetoder än.',
    paymentAddMethod: 'Lägg till betalmetod',
    paymentYourTitle: 'Dina betalmetoder',
    paymentFormAddCard: 'Lägg till nytt kort',
    paymentLabelCardNumber: 'Kortnummer',
    paymentLabelCardHolder: 'Kortinnehavare',
    paymentPlaceholderCardHolder: 'Namn på kort',
    paymentLabelExpiry: 'Utgångsdatum',
    paymentLabelCvv: 'CVV',
    paymentDefaultMethodCheckbox: 'Använd som standardbetalmetod',
    paymentSaveMethod: 'Spara betalmetod',
    paymentDefaultMethodBadge: 'Standardbetalmetod',
    paymentExpiresShort: 'Utgår:',
    paymentCardBrandGeneric: 'Kort',
    myPagesSettingsPageTitle: 'Inställningar',
    myPagesSettingsPageSubtitle: 'Hantera dina kontoinställningar',
    settingsChangePasswordTitle: 'Ändra lösenord',
    settingsCurrentPassword: 'Nuvarande lösenord',
    settingsNewPassword: 'Nytt lösenord',
    settingsConfirmNewPassword: 'Bekräfta nytt lösenord',
    settingsUpdatePassword: 'Uppdatera lösenord',
    settingsNotificationsTitle: 'Notifieringar',
    settingsNotifyOrders: 'E-postnotifieringar om beställningar',
    settingsNotifyNewsletter: 'Nyhetsbrev och erbjudanden',
    settingsNotifySms: 'SMS-notifieringar',
    wishlistLoading: 'Laddar dina favoriter...',
    wishlistRemoveFromTitle: 'Ta bort från favoriter',
    logisticsTitle: 'Leveransöversikt',
    logisticsSubtitle: 'Följ dina leveranser i realtid',
    logisticsLastUpdated: 'Senast uppdaterad:',
    logisticsTrackingLabel: 'Spårningsnummer:',
    logisticsStatusDeliveredShort: 'Levererad',
    logisticsStatusTransportShort: 'Under transport',
    logisticsStatusPackingShort: 'Packas',
    logisticsStatusConfirmedShort: 'Bekräftad',
    logisticsDeliveredPrefix: 'Levererad ',
    logisticsEstimatedPrefix: 'Beräknad leverans: ',
    logisticsSeeOrderDetails: 'Se orderdetaljer',
    logisticsNoShipmentsTitle: 'Inga aktiva leveranser',
    logisticsNoShipmentsBody:
      'Du har för närvarande inga aktiva leveranser att spåra. När du gör en beställning kommer den att visas här.',
    logisticsInfoFastTitle: 'Snabb leverans',
    logisticsInfoFastBody:
      'Vi levererar dina produkter inom 3–5 arbetsdagar med våra pålitliga transportpartners.',
    logisticsInfoRealtimeTitle: 'Realtidsspårning',
    logisticsInfoRealtimeBody:
      'Följ din leverans i realtid med detaljerad spårningsinformation och leveransstatus.',
    logisticsInfoSupportTitle: 'Kundsupport',
    logisticsInfoSupportBody:
      'Vår kundsupport finns tillgänglig för att hjälpa dig med alla frågor om din leverans.',
    logisticsPartnersTitle: 'Våra leveranspartners',
    logisticsPartnersMore: 'Fler partners',
    logisticsFaqTitle: 'Vanliga frågor',
    logisticsFaq1Q: 'Hur spårar jag min leverans?',
    logisticsFaq1A:
      'Du kan spåra din leverans direkt från sidan "Mina beställningar" där du ser alla dina aktiva leveranser med spårningsnummer och status.',
    logisticsFaq2Q: 'Vad gör jag om paketet inte kommer?',
    logisticsFaq2A:
      'Kontakta oss via kontaktformuläret om din leverans är försenad mer än 5 arbetsdagar. Vi hjälper dig att spåra paketet.',
    logisticsFaq3Q: 'Kan jag ändra leveransadress?',
    logisticsFaq3A:
      'Adressändringar är möjliga fram till dess att ordern har skickats från vårt lager. Kontakta oss snarast för ändringar.',

    // Auth
    register: 'Registrera',
    email: 'E-postadress',
    password: 'Lösenord',
    name: 'Fullständigt namn',
    confirmPassword: 'Bekräfta lösenord',
    welcomeBack: 'Välkommen tillbaka',
    loginSubtitle: 'Logga in på ditt konto för att fortsätta.',
    createAccount: 'Skapa ditt konto',
    createAccountSubtitle: 'Börja handla idag',
    fullName: 'Fullständigt namn',
    yourEmail: 'din@email.com',
    minChars: 'Minst 6 tecken',
    passwordStrengthWeak: 'Svagt',
    passwordStrengthMedium: 'Medel',
    passwordStrengthStrong: 'Starkt',
    alreadyHaveAccount: 'Har du redan ett konto?',
    noAccount: 'Har du inget konto?',
    loginHere: 'Logga in här',
    createAccountHere: 'Skapa ett konto här.',
    loggingIn: 'Loggar in...',
    creatingAccount: 'Skapar konto...',
    createAccountBtn: 'Skapa konto',
    passwordsMatch: 'Lösenorden matchar',
    passwordsDontMatch: 'Lösenorden matchar inte',
    fillAllFields: 'Vänligen fyll i alla fält',
    wrongCredentials: 'Felaktig e-post eller lösenord',
    emailAlreadyExists: 'E-postadressen är redan registrerad',
    passwordTooShort: 'Lösenordet måste vara minst 6 tecken',
    termsText: 'Genom att registrera dig godkänner du våra användarvillkor och integritetspolicy',
    
    // Footer - About Us
    aboutUs: 'Om oss',
    aboutCompany: 'Om företaget',
    career: 'Karriär',
    sustainability: 'Hållbarhet',
    press: 'Press',
    
    // Footer - Customer Service
    customerService: 'Kundservice',
    contactUs: 'Kontakta oss',
    shippingDelivery: 'Frakt & Leverans',
    returnsExchanges: 'Returer & Byten',
    faq: 'Vanliga frågor',
    sizeGuide: 'Storleksguide',
    
    // Footer - Terms
    terms: 'Villkor',
    termsOfPurchase: 'Köpvillkor',
    privacyPolicy: 'Integritetspolicy',
    cookies: 'Cookies',
    rightOfWithdrawal: 'Ångerrätt',
    
    // Footer - Other
    followUs: 'Följ oss',
    allRightsReserved: 'Alla rättigheter förbehållna.',
    paymentMethods: 'Betalningsmetoder',
    deliveryMethods: 'Leveransmetoder',
    
    // Reviews
    reviews: 'Recensioner',
    writeReview: 'Skriv en recension',
    reviewTitle: 'Rubrik',
    reviewBody: 'Din recension',
    reviewRating: 'Betyg',
    submitReview: 'Skicka recension',
    noReviews: 'Inga recensioner ännu. Bli den första att recensera!',
    verifiedPurchase: 'Verifierat köp',
    
    // Delivery Info
    deliveryInfo: 'Leveransinformation',
    deliveryTime: 'Leveranstid',
    deliveryTimeValue: '3-5 arbetsdagar',
    freeShipping: 'Fri frakt över 500 kr',
    freeShippingInfo: 'Fri frakt över 500 kr',
    returnPolicy: 'Returpolicy',
    returnPolicyValue: '14 dagars ångerrätt',
    
    // Breadcrumbs
    breadcrumbsHome: 'Hem',
    breadcrumbsProducts: 'Produkter',
    
    // Misc
    ecommerce: 'E-handel',
    companyName: 'Boxshe',
    
    // Categories
    categoryClothes: 'Kläder',
    categoryShoes: 'Skor',
    categoryAccessories: 'Accessoarer',
    categoryJewelry: 'Smycken',
    categoryElectronics: 'Elektronik',
    categoryHomeDecor: 'Hem & Inredning',
    categorySportsFitness: 'Sport & Fritid',
    categoryBeauty: 'Skönhet',
    categoryKids: 'Barn',
    categoryMen: 'Herr',
    categoryWomen: 'Dam',
    categoryAll: 'Alla',
    
    // Wishlist
    wishlist: 'Önskelista',
    yourSavedFavorites: 'Dina sparade favoritprodukter',
    emptyWishlist: 'Din önskelista är tom',
    noSavedProducts: 'Du har inte sparat några produkter än.',
    startShopping: 'Börja handla',
    
    // Contact Page
    contactPageTitle: 'Kontakta oss',
    contactPageSubtitle: 'Har du frågor, synpunkter eller behöver hjälp? Vi finns här för dig och svarar så snart vi kan.',
    contactInfo: 'Kontaktuppgifter',
    address: 'Adress',
    phone: 'Telefon',
    openingHours: 'Mån–Fre: 08:00–17:00',
    weRespondWithin24h: 'Vi svarar inom 24 timmar',
    organizationNumber: 'Organisationsnummer',
    sendMessage: 'Skicka ett meddelande',
    yourName: 'Ditt namn',
    subject: 'Ämne',
    selectSubject: 'Välj ämne',
    orderQuestion: 'Fråga om beställning',
    returnComplaint: 'Retur och reklamation',
    productQuestion: 'Produktfråga',
    sustainabilityQuestion: 'Hållbarhet',
    other: 'Annat',
    message: 'Meddelande',
    writeMessageHere: 'Skriv ditt meddelande här...',
    sendMessageBtn: 'Skicka meddelande',
    commonQuestions: 'Vanliga frågor',
    howLongDelivery: 'Hur lång är leveranstiden?',
    deliveryAnswer: 'Standardleverans tar 3–5 arbetsdagar. Expressleverans finns tillgänglig vid utcheckning.',
    whichPaymentMethods: 'Vilka betalningsmetoder accepterar ni?',
    paymentAnswer: 'Vi accepterar kortbetalning (Visa, Mastercard) och Klarna delbetalning.',
    howReturns: 'Hur fungerar returer?',
    returnsAnswer: 'Du har 30 dagars öppet köp. Returfrakt är kostnadsfri med vår returetikett.',
    canChangeOrder: 'Kan jag ändra eller avbryta en beställning?',
    changeOrderAnswer: 'Kontakta kundservice inom 30 minuter efter beställningen så hjälper vi dig.',
    deliverOutsideSweden: 'Levererar ni utanför Sverige?',
    outsideSwedenAnswer: 'Ja, vi levererar till hela Norden och EU. Fraktkostnaden varierar beroende på destination.',
    
    // Terms of Purchase Page
    termsOfPurchaseTitle: 'Köpvillkor',
    termsOfPurchaseIntro: 'Här finner du de allmänna villkor som gäller vid köp från vår webbplats.',
    lastUpdated: 'Senast uppdaterad:',
    generalTerms: 'Allmänna villkor',
    generalTermsText: 'Dessa allmänna villkor gäller för alla köp som görs via vår webbplats. Genom att beställa från oss accepterar du dessa villkor. Villkoren utgör tillsammans med din orderbekräftelse det avtal som gäller mellan dig och oss. Vi förbehåller oss rätten att ändra dessa villkor. Vid varje beställning gäller de villkor som är publicerade på webbplatsen vid beställningstillfället. För att handla hos oss måste du ha fyllt 18 år. Vi accepterar inte beställningar från minderåriga utan målsmans godkännande.',
    pricesAndPayment: 'Priser och betalning',
    pricesAndPaymentText: 'Alla priser anges i USD och inkluderar moms. Vid beställning från länder utanför Sverige kan ytterligare tullavgifter och skatter tillkomma. Vi erbjuder följande betalningsmetoder: kortbetalning (Visa, Mastercard) och Klarna delbetalning. Betalning sker i samband med beställning. Vid delbetalning via Klarna gäller Klarnas egna villkor, vilka du accepterar i samband med betalningen. Vi förbehåller oss rätten att justera priser på webbplatsen utan föregående avisering. Gällande pris är det som anges på webbplatsen vid beställningstillfället.',
    delivery: 'Leverans',
    deliveryText: 'Standardleverans tar 3–5 arbetsdagar inom Sverige. Expressleverans med 1–2 arbetsdagar finns som tillval vid utcheckning. Leveranser sker med PostNord, DHL eller Budbee beroende på valt leveranssätt och destination. Vid beställning över $500 erbjuder vi fri standardfrakt inom Sverige. För beställningar under $500 tillkommer en fraktavgift om $39 för standardfrakt och $79 för expressfrakt. Om en vara är tillfälligt slut i lager informerar vi dig via e-post med beräknad leveranstid. Du har då rätt att häva köpet om leveranstiden inte passar.',
    rightOfWithdrawalSection: 'Ångerrätt och returer',
    rightOfWithdrawalText: 'Enligt lagen om distansavtal har du 14 dagars ångerrätt från det att du mottagit varan. Vi erbjuder utökat öppet köp om 30 dagar. För att utnyttja ångerrätten måste varan vara oanvänd och i samma skick som när du mottog den. Alla etiketter och förpackningar ska vara kvar. Returfrakt är alltid gratis. Kontakta vår kundservice för att få en returetikett. Vid åberopande av ångerrätten återbetalas hela köpesumman inom 14 dagar från det att vi mottagit varan. Undantag från ångerrätten gäller för varor med bruten förpackning, specialtillverkade produkter samt hygienartiklar och underkläder där förpackningen har brutits.',
    complaints: 'Reklamationer',
    complaintsTermsText: 'Enligt konsumentköplagen har du rätt att reklamera en vara inom tre år från inköpsdatum, förutsatt att felet fanns vid köpet. Reklamation ska ske inom skälig tid efter det att du upptäckt eller bort upptäcka felet. Reklamation som sker inom två månader från upptäckten anses alltid ha skett inom skälig tid. Vid godkänd reklamation står vi för returfrakten. Du har rätt att välja mellan reparation, ny vara, prisavdrag eller återbetalning. Kontakta vår kundservice för att påbörja en reklamation. Bifoga ordernummer och beskrivning av felet. Vi rekommenderar att du fotograferar felet för att underlätta hanteringen.',
    personalData: 'Personuppgifter',
    personalDataText: 'Vi behandlar dina personuppgifter i enlighet med GDPR och vår integritetspolicy. Du hittar den fullständiga integritetspolicyn under länken Integritetspolicy längst ner på sidan. De personuppgifter vi samlar in används för att hantera din beställning, leverans och betalning. Uppgifterna lagras säkert och delas endast med våra betalningsleverantörer och logistikpartners i den utsträckning som krävs för att fullfölja avtalet. Du har rätt att begära utdrag, rättelse eller radering av dina personuppgifter. Kontakta vår kundservice för frågor om personuppgiftshantering.',
    forceMajeure: 'Force majeure',
    forceMajeureText: 'Vi är befriade från påföljd för underlåtenhet att fullgöra vissa förpliktelser enligt dessa villkor, om underlåtenheten har sin grund i befriande omständigheter enligt nedan och omständigheten förhindrar, försvårar eller försenar fullgörelsen. Såsom befriande omständighet ska anses vara bland annat myndighets åtgärd eller underlåtenhet, nytillkommen eller ändrad lagstiftning, konflikt på arbetsmarknaden, blockad, brand, översvämning, sabotage, olyckshändelse av större omfattning eller annan typ av naturkatastrof. I force majeure-fall har vi rätt att häva avtalet utan skyldighet att betala skadestånd.',
    disputes: 'Tvist',
    disputesText: 'Vi strävar alltid efter att lösa eventuella tvister i samförstånd med dig. Om vi trots detta inte skulle lyckas nå en överenskommelse kan du vända dig till Allmänna reklamationsnämnden (ARN). Du kan också använda EU-kommissionens onlineplattform för tvistlösning (ODR), som finns tillgänglig på http://ec.europa.eu/odr. Eventuell tvist ska i första hand lösas genom förhandling. Om parterna inte kan enas ska tvisten avgöras av svensk allmän domstol med tillämpning av svensk rätt.',
    questionsAboutTerms: 'Har du frågor om våra villkor?',
    questionsAboutTermsText: 'Kontakta vår kundservice om något är oklart eller om du behöver hjälp med en beställning.',
    
    // Privacy Policy Page
    privacyPolicyTitle: 'Integritetspolicy',
    privacyPolicyIntro: 'Din integritet är viktig för oss. Här beskriver vi hur vi samlar in, använder och skyddar dina personuppgifter.',
    whoAreWe: 'Vem är vi?',
    whoAreWeText1: 'E-handel AB (org.nr 556123-4567) är personuppgiftsansvarig för behandlingen av dina personuppgifter på denna webbplats.',
    whoAreWeText2: 'Vår adress är Storgatan 12, 111 22 Stockholm. Du når vår kundservice på kundservice@example.se eller telefon +46 (0)8-123 45 67.',
    whatDataCollect: 'Vilka uppgifter samlar vi in?',
    whatDataCollectText1: 'Vi samlar in de personuppgifter som du själv lämnar till oss när du gör en beställning, kontaktar kundservice eller anmäler dig till vårt nyhetsbrev. Detta kan inkludera namn, adress, e-postadress, telefonnummer och betalningsuppgifter.',
    whatDataCollectText2: 'Vi samlar även in teknisk information om din enhet och din användning av webbplatsen, såsom IP-adress, webbläsartyp, operativsystem och besöksstatistik, via cookies och liknande tekniker.',
    whyProcessData: 'Varför behandlar vi dina uppgifter?',
    whyProcessDataText1: 'Vi behandlar dina personuppgifter för att kunna fullgöra vårt avtal med dig, det vill säga hantera din beställning, leverera varor och hantera betalningar.',
    whyProcessDataText2: 'Uppgifterna används också för kundservice, reklamationer och returer. Med ditt samtycke kan vi använda uppgifterna för marknadsföring och nyhetsbrev.',
    whyProcessDataText3: 'Vi analyserar besöksdata för att förbättra vår webbplats, anpassa vårt utbud och förebygga bedrägerier.',
    legalBasis: 'Rättslig grund',
    legalBasisText1: 'Behandlingen av dina personuppgifter grundar sig på följande rättsliga grunder enligt GDPR:',
    legalBasisText2: 'Avtal — för att fullgöra köpavtalet med dig.',
    legalBasisText3: 'Rättslig förpliktelse — för att uppfylla bokföringskrav och konsumenträttsliga lagar.',
    legalBasisText4: 'Berättigat intresse — för att förebygga bedrägeri, säkerställa teknisk drift och analysera webbtrafik.',
    legalBasisText5: 'Samtycke — för marknadsföring och nyhetsbrev. Du kan när som helst återkalla ditt samtycke.',
    howLongStore: 'Hur länge sparar vi uppgifterna?',
    howLongStoreText1: 'Vi sparar dina personuppgifter endast så länge som det är nödvändigt för de ändamål som anges i denna policy.',
    howLongStoreText2: 'Order- och betalningsuppgifter sparas i enlighet med bokföringslagen (minst 7 år). Kundkontoinformation sparas så länge du har ett aktivt konto. Marknadsföringsrelaterade uppgifter sparas tills du återkallar ditt samtycke.',
    whoShareWith: 'Vem delar vi uppgifter med?',
    whoShareWithText1: 'Vi delar endast dina uppgifter med utvalda partners som hjälper oss att driva vår verksamhet, och endast i den utsträckning som krävs.',
    whoShareWithText2: 'Detta inkluderar logistikpartners (PostNord, DHL, DB Schenker) för leverans, betalningsleverantörer (Klarna, Stripe) för transaktionshantering och IT-leverantörer för drift av webbplatsen.',
    whoShareWithText3: 'Vi säljer aldrig dina personuppgifter till tredje part för marknadsföringsändamål.',
    yourRights: 'Dina rättigheter',
    yourRightsText1: 'Enligt GDPR har du följande rättigheter vad gäller dina personuppgifter:',
    yourRightsText2: 'Rätt till tillgång — begära ett utdrag över vilka uppgifter vi har om dig.',
    yourRightsText3: 'Rätt till rättelse — begära att felaktiga uppgifter korrigeras.',
    yourRightsText4: 'Rätt till radering — begära att dina uppgifter raderas ("rätten att bli bortglömd"), med vissa undantag enligt lag.',
    yourRightsText5: 'Rätt till begränsning — begära att behandlingen av dina uppgifter begränsas.',
    yourRightsText6: 'Rätt till dataportabilitet — få ut dina uppgifter i ett strukturerat format.',
    yourRightsText7: 'Rätt att göra invändningar — invända mot behandling baserad på berättigat intresse eller direktmarknadsföring.',
    contactAndComplaints: 'Kontakt och klagomål',
    contactAndComplaintsText1: 'Om du har frågor om vår personuppgiftshantering eller vill utöva dina rättigheter, kontakta vår kundservice på kundservice@example.se.',
    contactAndComplaintsText2: 'Om du anser att vi inte har hanterat dina personuppgifter korrekt har du rätt att lämna in ett klagomål till Datainspektionen (Integritetsskyddsmyndigheten, IMY).',
    questionsAboutPrivacy: 'Har du frågor om vår integritetspolicy?',
    questionsAboutPrivacyText: 'Kontakta vår kundservice om du har frågor om hur vi hanterar dina personuppgifter.',
    contactCustomerService: 'Kontakta kundservice',
    
    // Cookies Page
    cookiesTitle: 'Cookies',
    cookiesIntro: 'Information om hur vi använder cookies och hur du hanterar dina inställningar',
    whatAreCookies: 'Vad är cookies?',
    whatAreCookiesText1: 'Cookies är små textfiler som lagras på din dator, surfplatta eller mobiltelefon när du besöker en webbplats. De används för att webbplatsen ska kunna känna igen din enhet vid återbesök.',
    whatAreCookiesText2: 'Cookies är vanliga på internet och utgör en viktig del av hur moderna webbplatser fungerar. Utan cookies skulle många funktioner, såsom inloggning, varukorg och språkinställningar, inte fungera korrekt.',
    howUseCookies: 'Hur använder vi cookies?',
    howUseCookiesText: 'Vi använder cookies för att förbättra din upplevelse på vår webbplats, analysera trafik och anpassa vårt innehåll. Nedan beskriver vi de olika kategorier av cookies vi använder.',
    necessaryCookies: 'Nödvändiga cookies',
    necessaryCookiesText1: 'Dessa cookies är nödvändiga för att webbplatsen ska fungera korrekt. De kan inte stängas av i våra system och lagrar inga personligt identifierbara uppgifter.',
    necessaryCookiesText2: 'Exempel: sessionscookies för varukorgen, inloggningsstatus och säkerhetsfunktioner.',
    functionalCookies: 'Funktionella cookies',
    functionalCookiesText1: 'Funktionella cookies gör det möjligt för webbplatsen att komma ihåg val du gör (t.ex. språk, region eller valuta) och ge förbättrade, mer personliga funktioner.',
    functionalCookiesText2: 'Exempel: språkinställningar, sparade inloggningsuppgifter och anpassade preferenser.',
    analyticalCookies: 'Analytiska cookies',
    analyticalCookiesText1: 'Dessa cookies hjälper oss att förstå hur besökare använder vår webbplats genom att samla in och rapportera information anonymt. Informationen används för att förbättra webbplatsens struktur och innehåll.',
    analyticalCookiesText2: 'Exempel: Google Analytics, besöksstatistik, sidvisningar och trafikkällor.',
    marketingCookies: 'Marknadsföringscookies',
    marketingCookiesText1: 'Marknadsföringscookies används för att spåra besökare över webbplatser. Avsikten är att visa annonser som är relevanta och engagerande för den enskilda användaren.',
    marketingCookiesText2: 'Exempel: sociala medier-pixel, remarketing och annonspartners.',
    howManageCookies: 'Hur hanterar du cookies?',
    howManageCookiesText1: 'Du kan när som helst ändra dina cookie-inställningar genom att klicka på knappen nedan eller genom att justera inställningarna i din webbläsare.',
    howManageCookiesText2: 'Observera att inaktivering av vissa cookies kan påverka funktionaliteten på vår webbplats och göra att vissa tjänster inte fungerar som förväntat.',
    howManageCookiesText3: 'De flesta webbläsare låter dig kontrollera cookies via sina inställningar. Information om hur du gör detta finns i hjälpmenyn för din webbläsare.',
    thirdPartyCookies: 'Tredjepartscookies',
    thirdPartyCookiesText1: 'Vissa cookies på vår webbplats sätts av tredje parter, såsom betalningsleverantörer och analysverktyg. Dessa parter har sina egna integritetspolicyer och vi rekommenderar att du läser dem.',
    thirdPartyCookiesText2: 'Vi använder i dagsläget följande tredjepartstjänster som kan sätta cookies: Google Analytics (analys), Klarna (delbetalning) och Meta Pixel (marknadsföring).',
    cookiesContact: 'Kontakt',
    cookiesContactText: 'Om du har frågor om vår användning av cookies är du välkommen att kontakta vår kundservice på kundservice@example.se.',
    manageCookies: 'Hantera dina cookies',
    manageCookiesText: 'Uppdatera dina cookie-inställningar eller kontakta oss vid frågor',
    cookieSettings: 'Cookie-inställningar',
    cookieBannerIntro: 'Vi använder cookies för att förbättra din upplevelse.',
    cookieReadMore: 'Läs mer',
    cookieCustomize: 'Anpassa',
    cookieAccept: 'Acceptera',
    cookieSettingsSubtitle: 'Välj vilka cookies du vill tillåta',
    cookieRequiredBadge: '(Krävs)',
    cookieRejectAll: 'Avvisa alla',
    cookieSave: 'Spara',
    cookieAcceptAll: 'Acceptera alla',
    shippingFreeOverShort: 'Fri frakt över 500 kr',
    closeSearchAria: 'Stäng sökning',
    searchSuggestionsTitle: 'Sökförslag',
    recentSearchesTitle: 'Senaste sökningar',
    clearRecentSearches: 'Rensa',
    popularSearchesTitle: 'Populära sökningar',
    searchButtonLabel: 'Sök',
    didYouMeanPrefix: 'Menade du',
    swedishSecondary: 'Swedish',
    englishSecondary: 'Engelska',
    catalogTitleAll: 'Alla produkter',
    catalogTitleCategorySuffix: 'produkter',
    catalogCategoryLine: 'Visar {count} produkter i kategorin "{cat}"',
    catalogAllLine: 'Visar {count} produkter från vårt sortiment',
    catalogEmptyCategoryTitle: 'Inga produkter i denna kategori',
    catalogEmptyGeneralTitle: 'Inga produkter tillgängliga',
    catalogEmptyCategoryHint: 'Vi kunde inte hitta några produkter i kategorin "{cat}".',
    catalogEmptyDbBody: 'Det verkar vara ett problem med databasanslutningen.',
    catalogReturnToHome: 'Till startsidan',
    catalogFooterLine: 'Visar {shown} av {total} produkter',
    
    // Right of Withdrawal Page
    rightOfWithdrawalTitle: 'Ångerrätt',
    rightOfWithdrawalIntro: 'Din lagstadgade rätt att ångra ett distansköp inom 14 dagar. Vi erbjuder utökat öppet köp på 30 dagar.',
    yourRightOfWithdrawal: 'Din ångerrätt',
    yourRightOfWithdrawalText1: 'Enligt lagen (2005:59) om distansavtal har du rätt att frånträda ett distansavtal inom 14 kalenderdagar från det att du mottagit varan.',
    yourRightOfWithdrawalText2: 'Vi erbjuder utökat öppet köp och ger dig 30 dagar på dig att bestämma om du vill behålla din vara. Ångerfristen börjar löpa från den dag du mottog varan.',
    yourRightOfWithdrawalText3: 'Ångerrätten gäller under förutsättning att varan returneras i väsentligen oförändrat skick. Varan får gärna provas, men den ska inte ha använts eller skadats.',
    howToWithdraw: 'Så här ångrar du ett köp',
    howToWithdrawText1: 'Kontakta vår kundservice på kundservice@example.se eller använd formuläret nedan.',
    howToWithdrawText2: 'Ange ditt ordernummer och vilka varor du vill returnera.',
    howToWithdrawText3: 'Vi skickar en kostnadsfri returetikett till dig.',
    howToWithdrawText4: 'Packa varan i originalförpackningen med alla etiketter och tillbehör.',
    howToWithdrawText5: 'Lämna in paketet enligt instruktionerna på returetiketten.',
    refund: 'Återbetalning',
    refundText1: 'Vi återbetalar alla betalningar vi mottagit från dig, inklusive leveranskostnader, senast inom 14 dagar från det att vi mottagit ditt meddelande om ånger.',
    refundText2: 'Vi väntar med återbetalningen tills vi mottagit varan tillbaka alternativt du tillhandahållit oss bevis på att varan returnerats.',
    refundText3: 'Återbetalningen sker via samma betalningsmetod som användes vid köpet.',
    exceptionsFromWithdrawal: 'Undantag från ångerrätten',
    exceptionsFromWithdrawalText: 'Ångerrätten gäller inte för följande varor enligt lag:',
    exceptionsFromWithdrawalText1: 'Varor som tillverkats enligt dina anvisningar eller har en tydlig personlig prägel.',
    exceptionsFromWithdrawalText2: 'Varor som på grund av sin beskaffenhet kan bli förstörda eller föråldrade snabbt.',
    exceptionsFromWithdrawalText3: 'Förseglade varor som av hälso- eller hygieniska skäl inte lämpar sig att returnera, om förseglingen brutits.',
    exceptionsFromWithdrawalText4: 'Ljud- och bildupptagningar eller programvara i förseglad förpackning, om förseglingen brutits.',
    exceptionsFromWithdrawalText5: 'Tidningar, tidskrifter eller magasin med undantag för prenumerationsavtal.',
    needHelpWithReturn: 'Behöver du hjälp med din retur?',
    needHelpWithReturnText: 'Vår kundservice hjälper dig med alla frågor om ångerrätt och returer.',

    // About Us Page
    aboutUsTitle: 'Om oss',
    aboutUsSubtitle: 'Vi startade Boxshe för att göra det enkelt att hitta bra produkter till ett rimligt pris – med service som faktiskt fungerar.',
    customerSatisfaction: 'Kundnöjdhet',
    yearsInBusiness: 'År i branschen',
    employees: 'Anställda',
    customersCount: 'Kunder',
    productsCount: 'Produkter',
    ourMission: 'Vad vi gör',
    ourMissionText: 'Vi väljer ut produkter vi själva skulle köpa och ser till att de når dig snabbt och i gott skick. Det är egentligen så enkelt.',
    handpickedProducts: 'Noggrant utvalda produkter',
    fastSecureDeliveries: 'Pålitliga leveranser',
    personalCustomerService: 'Kundservice som svarar på riktigt',
    ourCoreValues: 'Det vi tror på',
    quality: 'Kvalitet',
    qualityDesc: 'Vi säljer bara produkter vi är nöjda med själva. Håller inte en vara måttet tar vi tillbaka den.',
    sustainabilityTitle: 'Hållbarhet',
    sustainabilityDesc: 'Vi arbetar aktivt för att minska vår miljöpåverkan i alla led.',
    innovation: 'Enkelhet',
    innovationDesc: 'Att handla online ska vara smidigt. Vi jobbar hela tiden med att ta bort onödiga steg.',
    ourHistory: 'Vår historia',
    history2020Title: 'Starten',
    history2020Text: 'Företaget grundades med en vision om en bättre e-handel.',
    history2022Title: 'Expansion',
    history2022Text: 'Vi expanderade till hela Norden och flyttade till nytt lager.',
    history2024Title: 'Framtiden',
    history2024Text: 'Vi fortsätter att växa och utveckla vårt sortiment.',
    joinOurTeam: 'Bli en del av vårt team',
    joinOurTeamText: 'Vi letar alltid efter talangfulla människor som vill växa med oss.',
    seeVacancies: 'Se lediga tjänster',
    customers: 'Kunder',
    trust: 'Ärlighet',
    trustDesc: 'Vi är tydliga med vad som gäller – priser, leveranstider och returvillkor utan krångel.',
    ourJourney: 'Vår historia',
    ourJourneyText1: 'Boxshe grundades 2009 av ett gäng som tröttnat på att e-handel antingen var dyr, opålitlig eller båda. Vi ville visa att det gick att göra bättre – med ett smalt och välvalt sortiment, ärliga priser och en kundservice som faktiskt hjälper.',
    ourJourneyText2: 'Sedan dess har vi vuxit stadigt. Idag har vi kunder i hela Norden och ett team på drygt 50 personer som jobbar hårt för att varje beställning ska kännas rätt. Vi är fortfarande ett familjeföretag och det märks i hur vi jobbar.',
    keyMilestones: 'Milstolpar',
    founding: 'Grundande',
    foundingDesc: 'Boxshe öppnar med ett litet men noggrant utvalt sortiment.',
    expansion: 'Expansion',
    expansionDesc: 'Eget lager i Stockholm och leveranser till hela Sverige.',
    digitalTransformation: 'Ny plattform',
    digitalTransformationDesc: 'Ny webbplats och förbättrad orderhantering.',
    internationalExpansion: 'Norden',
    internationalExpansionDesc: 'Leveranser till Norge, Danmark, Finland och Island.',
    meetOurTeam: 'Möt vårt team',
    ceo: 'VD',
    ceoDesc: '15+ års erfarenhet av e-handel och digital transformation',
    cto: 'CTO',
    ctoDesc: 'Expert på skalbara e-handelsplattformar och systemarkitektur',
    cmo: 'CMO',
    cmoDesc: 'Specialist på digital marknadsföring och kundupplevelser',
    ourVisionForFuture: 'Framåt',
    visionText: 'Vi siktar på att fortsätta växa i Norden och ta in fler produktkategorier. Men vi tänker inte växa snabbare än vi kan hålla kvaliteten uppe.',
    sustainabilityVision: 'Hållbarhet',
    sustainabilityVisionDesc: 'Miljömedvetna leveranser och hållbara produkter',
    growth: 'Tillväxt',
    growthDesc: 'Expandera till nya marknader och kundsegment',
    community: 'Gemenskap',
    communityDesc: 'Bygga starka relationer med kunder och partners',
    swedishEcommerce: 'Svensk e-handel',
    swedishEcommerceDesc: 'Certifierad medlem i Svensk Digital Handel',
    iso9001: 'ISO 9001',
    iso9001Desc: 'Kvalitetscertifiering för ledningssystem',
    gazelle: 'Gasell',
    gazelleDesc: 'Utsett till Gasellföretag 2023',
    partnerships: 'Partnerskap',
    environmentalCommitment: 'Miljöengagemang',
    environmentalCommitmentDesc: 'Klimatneutrala leveranser och 100% förnybar energi i våra lager',
    sustainabilityCommitment: 'Hållbara förpackningar',
    sustainabilityCommitmentDesc: 'Alla våra förpackningar är återvinningsbara och vi använder minimalt med fyllnadsmaterial.',
    technologyInnovation: 'Teknik & innovation',
    modernTechnology: 'Modern teknik',
    modernTechnologyDesc: 'Avancerad teknik för personalisering och optimering',
    cloudNative: 'Cloud native',
    cloudNativeDesc: 'Byggd på modern molninfrastruktur för skalbarhet',
    fastDeliveries: 'Snabba leveranser',
    fastDeliveriesDesc: 'Automatiserade processer för snabb orderhantering',

    popularProductsTitle: 'Populära produkter',
    popularProductsSubtitle: 'Utvalda plagg från vårt sortiment.',
    productImagePlaceholder: 'Produktbild',
    featuredViewAllProducts: 'Se alla produkter',
    shopByCategoryTitle: 'Shoppa efter kategori',
    shopByCategorySubtitle: 'Upptäck våra populära kategorier och hitta precis det du letar efter',
    categoryProductCount: 'produkter',
    comingSoonLabel: 'Kommer snart',
    catIconSweater: 'Tröja',
    catIconMen: 'Herr',
    catIconWomen: 'Dam',
    catIconTrousers: 'Byxor',
    catIconDress: 'Klänning',
    catIconJacket: 'Jacka',
    catIconTshirt: 'T-shirt',
    heroBannerFreeShipping: 'Fri frakt – villkor gäller',
    heroBannerFreeReturns: 'Kostnadsfria returer',
    heroBannerNoHiddenFees: 'Inga dolda avgifter',
    heroCatSuperDeals: 'Superdeals',
    heroCatTopTrends: 'Toptrender',
    heroCatBrandZone: 'Varumärken',
    heroCatFlashSale: 'Blixtrea',
    heroCatNewIn: 'Nyheter',
    heroLoadMore: 'Visa fler',
    heroLoading: 'Laddar...',
    heroSeenAllInCategory: 'Du har sett alla produkter i kategorin "{category}"',
    heroExploreOtherCategories: 'Utforska andra kategorier →',
    heroAddToCartAria: 'Lägg i varukorg',
    heroWishlistAria: 'Lägg till i önskelista',
    gridRefreshingProducts: 'Uppdaterar produkter...',
    gridLoading: 'Laddar...',
    gridLoadMore: 'Visa fler',
    faqPageTitle: 'Vanliga frågor',
    faqPageSubtitle: 'Hitta snabba svar på dina frågor. Använd sök eller filtrera efter ämne nedan.',
    faqSearchPlaceholder: 'Sök bland frågor och svar...',
    faqNoResults: 'Inga frågor hittades',
    faqNoResultsHint: 'Prova en annan sökning eller kategori',
    faqContactTitle: 'Hittar du inte svaret?',
    faqContactSubtitle: 'Vår kundservice finns tillgänglig måndag–fredag och svarar vanligtvis inom 24 timmar.',
    faqContactButton: 'Kontakta kundservice',
    faqCatAll: 'Alla',
    faqCatDelivery: 'Leverans',
    faqCatPayment: 'Betalning',
    faqCatReturns: 'Returer',
    faqCatProducts: 'Produkter',
    faqCatCustomerService: 'Kundservice',

    // Sustainability Page
    sustainabilityPageTitle: 'Hållbarhet',
    sustainabilityPageSubtitle: 'Vi tar ansvar för vår påverkan – på miljön, på människor och i hela leveranskedjan.',
    sustainabilityPromise: 'Vårt hållbarhetslöfte',
    sustainabilityPromiseText: 'Vi är engagerade i att minska vår miljöpåverkan i alla led – från vilka produkter vi väljer in till hur vi packar och skickar dem.',
    climateNeutralDeliveries: 'Klimatneutrala leveranser',
    climateNeutralDeliveriesDesc: 'Alla våra leveranser är klimatneutrala genom klimatkompensation och val av miljövänliga transportalternativ.',
    circularEconomy: 'Cirkulär ekonomi',
    circularEconomyDesc: 'Vi återvinner och återanvänder material i hela vår kedja, från produktion till förpackning.',
    ethicalProduction: 'Etisk produktion',
    ethicalProductionDesc: 'Vi arbetar endast med leverantörer som uppfyller höga standarder för arbetsvillkor och mänskliga rättigheter.',
    miljoIBilder: 'Miljö i bilder',
    miljoIBilderDesc: 'Sju bilder som speglar vad vi arbetar för',
    solarEnergy: 'Solenergi & Förnybar energi',
    recyclingCircular: 'Återvinning & Cirkulär ekonomi',
    organicFarming: 'Organisk odling & Bomull',
    sustainableTransport: 'Hållbart transportsystem',
    rainforestCompensation: 'Regnskog & Klimatkompensation',
    cleanWater: 'Rent vatten & Vattenvård',
    localCommunityFairTrade: 'Lokal gemenskap & Fair Trade',
    environmentalResponsibility: 'Miljöansvar',
    environmentalResponsibilityDesc: 'Skydda och återställa våra naturresurser genom medvetna val i varje led.',
    transparency: 'Transparens',
    transparencyDesc: 'Vi är öppna med vår påverkan och våra framsteg, med årliga hållbarhetsrapporter.',
    innovationSustainability: 'Innovation',
    innovationSustainabilityDesc: 'Vi söker ständigt nya hållbara lösningar för material, processer och logistik.',
    ourMainInitiatives: 'Våra huvudinitiativ',
    environmentalGoals2025: 'Miljömål 2025',
    goal1: '100% återvunna material i alla produkter',
    goal2: 'Noll koldioxidutsläpp från vår verksamhet',
    goal3: 'Alla förpackningar 100% återvinningsbara',
    goal4: 'Fair Trade-certifiering för alla produkter',
    goal5: '100% förnybar energi i alla våra lokaler',
    goal6: 'Noll vattenavfall i produktionen',
    responsibilityInChain: 'Ansvar i hela kedjan',
    responsibilityInChainText: 'Från råmaterial till färdig produkt tar vi ansvar för varje steg i vår leveranskedja. Våra produkter tillverkas under rättvisa förhållanden med respekt för både människa och miljö.',
    transparentTraceability: 'Transparent spårbarhet',
    transparentTraceabilityDesc: 'Vi kan spåra varje produkt tillbaka till källan med full insyn.',
    regularAudits: 'Regelbundna revisioner',
    regularAuditsDesc: 'Oberoende kontroller av alla våra leverantörer varje år.',
    longTermPartnerships: 'Långsiktiga partnerskap',
    longTermPartnershipsDesc: 'Vi bygger starka relationer med våra leverantörer över tid.',
    socialResponsibility: 'Socialt ansvar',
    charity: 'Välgörenhet',
    charityDesc: '1% av vår omsättning går till välgörenhetsorganisationer som arbetar med miljö och utbildning.',
    education: 'Utbildning',
    educationDesc: 'Stöd till utbildningsprojekt i våra produktionsländer för jämlikhet och framtidstro.',
    localEngagement: 'Lokalt engagemang',
    localEngagementDesc: 'Samarbete med lokala organisationer och projekt i samhällen där vi verkar.',
    sustainabilityMilestones: 'Hållbarhetsmilstolpar',
    milestone2020: 'Alla våra leveranser blev klimatneutrala genom klimatkompensation',
    milestone2021: 'Våra lokaler och lager drivs helt med förnybar energi',
    milestone2023: '50% av våra produkter är nu Fair Trade-certifierade',
    milestone2025: 'Mål: noll koldioxidutsläpp i hela verksamheten',
    certificationsAwards: 'Certifieringar & Utmärkelser',
    fairTrade: 'Fair Trade',
    fairTradeDesc: 'Certifierad för rättvis handel',
    bCorp: 'B Corp',
    bCorpDesc: 'Certifierad för social och miljömässig prestation',
    climateNeutralCert: 'Climate Neutral',
    climateNeutralCertDesc: 'Klimatneutral certifiering för hela verksamheten',
    makeADifference: 'Gör skillnad tillsammans',
    makeADifferenceText: 'Varje köp du gör hos oss bidrar till en mer hållbar framtid. Tillsammans kan vi skapa verklig förändring – för planeten, för människor och för kommande generationer.',
    exploreSustainableProducts: 'Utforska våra hållbara produkter',

    // Shipping & Delivery Page
    shippingAndDelivery: 'Frakt & Leverans',
    shippingSubtitle: 'Vi erbjuder globala leveranser. Standardfrakt 2-4 arbetsdagar, express 1-2 arbetsdagar.',
    deliveryOptions: 'Leveransalternativ',
    standardShipping: 'Standardfrakt',
    standardShippingTime: '2-4 arbetsdagar',
    standardShippingDesc: 'Global leverans • Fri frakt över $500',
    expressShipping: 'Expressleverans',
    expressShippingTime: '1-2 arbetsdagar',
    expressShippingDesc: 'Global leverans • Leverans till dörr',
    deliveryAreas: 'Leveransområden',
    sweden: 'Sverige',
    swedenDesc: 'Leverans till hela landet',
    nordics: 'Norden',
    nordicsDesc: 'Norge, Danmark, Finland, Island',
    eu: 'EU',
    euDesc: 'Alla EU-länder',
    restOfWorld: 'Övriga världen',
    restOfWorldDesc: 'Global leverans',
    trackYourDelivery: 'Spåra din leverans',
    trackYourDeliveryText: 'När din beställning har skickats får du ett e-postmeddelande med ett spårningsnummer. Du kan använda detta nummer för att följa din försändelse på transportörens webbplats.',
    transportMethods: 'Transportmetoder:',
    postnordDesc: 'PostNord – Globala leveranser',
    dhlDesc: 'DHL – Internationella frakter',
    schenkerDesc: 'DB Schenker – Logistiklösningar',
    deliveryTimes: 'Leveranstider',
    region: 'Region',
    deliveryTimeTable: 'Leveranstid',
    shippingPrice: 'Fraktpris',
    questionsAboutDelivery: 'Har du frågor om leverans?',
    questionsAboutDeliveryText: 'Kontakta vår kundservice så hjälper vi dig med spårning, leveransstatus eller andra frågor.',

    // Returns & Exchanges Page
    returnsAndExchanges: 'Returer & Byten',
    returnsSubtitle: 'Vi vill att du ska vara nöjd med ditt köp. Här hittar du all information om hur du returnerar eller byter en vara.',
    howToReturn: 'Så här returnerar du',
    registerReturn: '1. Registrera retur',
    registerReturnDesc: 'Logga in på ditt konto och registrera din retur digitalt.',
    packItem: '2. Paketera varan',
    packItemDesc: 'Packa varan i originalförpackningen med alla etiketter kvar.',
    sendBack: '3. Skicka tillbaka',
    sendBackDesc: 'Använd den medföljande returetiketten och lämna in paketet.',
    returnConditions: 'Returvillkor',
    thirtyDaysReturn: '30 dagars öppet köp',
    thirtyDaysReturnDesc: 'Du har alltid 30 dagars öppet köp från det att du mottagit din beställning.',
    freeReturnShipping: 'Gratis returfrakt',
    freeReturnShippingDesc: 'Vi skickar en returetikett utan extra kostnad vid alla returer.',
    unusedItems: 'Oanvända varor',
    unusedItemsDesc: 'Varan ska vara oanvänd och i obrutet originalskick med alla etiketter kvar.',
    refundCondition: 'Återbetalning',
    refundDesc: 'Återbetalning sker inom 5 arbetsdagar efter att vi mottagit din retur.',
    exchanges: 'Byten',
    exchangesText: 'Vill du byta till en annan storlek eller färg? Kontakta vår kundservice så hjälper vi dig med ditt byte. Byten är kostnadsfria inom 30 dagar från mottagandet.',
    exchangeSize: 'Byte till annan storlek',
    exchangeSizeDesc: 'Skicka tillbaka varan och ange önskad storlek vid returen. Vi skickar den nya storleken så snart vi mottagit din retur.',
    exchangeColor: 'Byte till annan färg',
    exchangeColorDesc: 'Om färgen inte stämmer överens med förväntan kan du enkelt byta till en annan färg inom 30 dagar.',
    complaintsTitle: 'Reklamationer',
    complaintsText: 'Har du fått en defekt eller felaktig vara? Vi ber om ursäkt för besväret och hjälper dig självklart att lösa det så snabbt som möjligt.',
    whenComplaining: 'Vid reklamation:',
    complaintStep1: 'Kontakta kundservice med ordernummer och bild på felet',
    complaintStep2: 'Vi skickar en kostnadsfri returetikett för reklamationen',
    complaintStep3: 'Du kan välja mellan ny vara eller full återbetalning',
    questionsAboutReturns: 'Har du frågor om returer?',
    questionsAboutReturnsText: 'Kontakta vår kundservice så hjälper vi dig med din retur, ditt byte eller din reklamation.',
  },
  en: {
    // Header & Navigation
    search: 'Search products...',
    login: 'Log in',
    logout: 'Log out',
    hello: 'Hello',
    cart: 'Shopping cart',
    menu: 'Menu',
    categories: 'Categories',
    deliveryDay: '24 working days',
    imageSearch: 'Image search',
    closeMenu: 'Close menu',
    goToMyPages: 'Go to My Pages',
    loginPrompt: 'Log in to see your orders and save favorites',
    searchProducts: 'Search on BOXSHE',
    quickLinks: 'Quick links',
    home: 'Home',
    information: 'Information',
    language: 'Language / Språk',
    swedish: 'Swedish',
    english: 'English',
    
    // Products
    products: 'Our Products',
    addToCart: 'Add to cart',
    outOfStock: 'Out of stock',
    productDetails: 'Product details',
    specifications: 'Specifications',
    description: 'Description',
    price: 'Price',
    category: 'Category',
    availability: 'Availability',
    inStock: 'In stock',
    outOfStockBadge: 'Out of stock',
    quantity: 'Quantity',
    addToCartBtn: 'Add to cart',
    colors: 'Colors',
    relatedProducts: 'Related products',
    loadMore: 'Load more',
    
    // Cart & Checkout
    total: 'Total',
    emptyCart: 'Your shopping cart is empty',
    continueShoppingBtn: 'Continue shopping',
    removeBtn: 'Remove',
    clearCartBtn: 'Clear cart',
    image: 'Image',
    goToCart: 'Go to cart',
    closeCart: 'Close cart',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
    removeProduct: 'Remove product',
    itemsSingular: 'item',
    itemsPlural: 'items',
    emptyCartHint: 'Browse the store — your selections will appear here.',
    pricePerUnit: 'ea.',
    cartEmptyBody: 'Start shopping to add products to your cart.',
    cartFreeShip1: 'Add ',
    cartFreeShip2: ' more for ',
    cartFreeShipFree: 'free shipping',
    cartFreeShip3: ' (on orders of 120 USD or more).',
    cartFreeShippingOnOrder: 'Free shipping on your order',
    cartNoImage: 'No image',
    cartSummaryTitle: 'Order summary',
    cartSubtotal: 'Subtotal',
    cartShipping: 'Shipping',
    cartShippingFree: 'Free',
    cartVatIncluded: 'Incl. VAT',
    goToCheckout: 'Go to checkout',
    cartTrustFast: 'Fast delivery',
    cartTrustSecure: 'Secure payment',
    cartTrustReturns: '30-day open purchase',

    // My account (Mina sidor)
    myPagesTitle: 'My account',
    myPagesWelcomeBack: 'Welcome back,',
    myPagesQuickActions: 'Quick actions',
    myPagesBackAria: 'Back to My account',
    myPagesLabelNameColon: 'Name:',
    myPagesLabelEmailColon: 'Email:',
    myPagesCardAccountTitle: 'Account information',
    myPagesCardAccountSubtitle: 'Manage your details',
    myPagesCardOrdersTitle: 'My orders',
    myPagesCardOrdersSubtitle: 'View your orders',
    myPagesCardOrdersBody: 'View and track your orders',
    myPagesCardAddressesTitle: 'Addresses',
    myPagesCardAddressesSubtitle: 'Manage delivery addresses',
    myPagesCardAddressesBody: 'Save and edit your addresses',
    myPagesCardPaymentTitle: 'Payment methods',
    myPagesCardPaymentSubtitle: 'Manage payment',
    myPagesCardPaymentBody: 'Save and manage payment methods',
    myPagesCardWishlistTitle: 'Wishlist',
    myPagesCardWishlistSubtitle: 'Saved products',
    myPagesCardWishlistBody: 'See your favourite products',
    myPagesCardSettingsTitle: 'Settings',
    myPagesCardSettingsSubtitle: 'Account settings',
    myPagesCardSettingsBody: 'Change password and preferences',
    myPagesAccountPageTitle: 'Account information',
    myPagesAccountPageSubtitle: 'Manage your personal details',
    myPagesPersonalDataTitle: 'Personal details',
    myPagesPersonalDataSubtitle: 'Update your account information',
    myPagesLabelName: 'Name',
    myPagesLabelEmailAddress: 'Email address',
    myPagesEdit: 'Edit',
    myPagesSaveChanges: 'Save changes',
    myPagesCancel: 'Cancel',
    myPagesOrdersPageTitle: 'My orders',
    myPagesOrdersPageSubtitle: 'View and track your orders',
    ordersLoading: 'Loading orders...',
    ordersFetchError: 'Could not load orders',
    ordersGenericError: 'Something went wrong while loading orders',
    ordersEmptyTitle: 'No orders yet',
    ordersEmptyBody: 'You have not placed any orders yet.',
    orderNumberLabel: 'Order number',
    orderDateLabel: 'Date',
    orderQtyShort: 'Qty:',
    orderSizeShort: 'Size:',
    orderColorShort: 'Colour:',
    orderLineImage: 'Image',
    orderTrackButton: 'Track order',
    paymentMethodCard: 'Card payment',
    orderStatusConfirmed: 'Confirmed',
    orderStatusPacking: 'Packing',
    orderStatusTransport: 'In transit',
    orderStatusDelivered: 'Delivered',
    paymentStatusPaid: 'Paid',
    paymentStatusPending: 'Awaiting payment',
    paymentStatusFailed: 'Payment failed',
    paymentStatusRefunded: 'Refunded',
    myPagesAddressesPageTitle: 'Addresses',
    myPagesAddressesPageSubtitle: 'Manage your delivery addresses',
    addressesEmptyTitle: 'No saved addresses',
    addressesEmptyBody: 'You have not saved any delivery addresses yet.',
    addressesAdd: 'Add address',
    addressesYourTitle: 'Your addresses',
    addressesFormTitle: 'Add new address',
    addressesLabelStreet: 'Street address',
    addressesPlaceholderStreet: 'Street address',
    addressesLabelPostal: 'Postal code',
    addressesLabelCity: 'City',
    addressesPlaceholderCity: 'City',
    addressesLabelPhone: 'Phone number',
    addressesPlaceholderPhone: '+1 555 000 0000',
    addressesDefaultCheckbox: 'Use as default address',
    addressesSave: 'Save address',
    addressesDefaultBadge: 'Default address',
    addressesSetDefault: 'Default',
    addressesPlaceholderFullName: 'First and last name',
    myPagesPaymentPageTitle: 'Payment methods',
    myPagesPaymentPageSubtitle: 'Manage your payment methods',
    paymentEmptyTitle: 'No saved payment methods',
    paymentEmptyBody: 'You have not saved any payment methods yet.',
    paymentAddMethod: 'Add payment method',
    paymentYourTitle: 'Your payment methods',
    paymentFormAddCard: 'Add new card',
    paymentLabelCardNumber: 'Card number',
    paymentLabelCardHolder: 'Cardholder name',
    paymentPlaceholderCardHolder: 'Name on card',
    paymentLabelExpiry: 'Expiry date',
    paymentLabelCvv: 'CVV',
    paymentDefaultMethodCheckbox: 'Use as default payment method',
    paymentSaveMethod: 'Save payment method',
    paymentDefaultMethodBadge: 'Default payment method',
    paymentExpiresShort: 'Expires:',
    paymentCardBrandGeneric: 'Card',
    myPagesSettingsPageTitle: 'Settings',
    myPagesSettingsPageSubtitle: 'Manage your account settings',
    settingsChangePasswordTitle: 'Change password',
    settingsCurrentPassword: 'Current password',
    settingsNewPassword: 'New password',
    settingsConfirmNewPassword: 'Confirm new password',
    settingsUpdatePassword: 'Update password',
    settingsNotificationsTitle: 'Notifications',
    settingsNotifyOrders: 'Email notifications about orders',
    settingsNotifyNewsletter: 'Newsletter and offers',
    settingsNotifySms: 'SMS notifications',
    wishlistLoading: 'Loading your favourites...',
    wishlistRemoveFromTitle: 'Remove from favourites',
    logisticsTitle: 'Delivery overview',
    logisticsSubtitle: 'Track your deliveries in real time',
    logisticsLastUpdated: 'Last updated:',
    logisticsTrackingLabel: 'Tracking number:',
    logisticsStatusDeliveredShort: 'Delivered',
    logisticsStatusTransportShort: 'In transit',
    logisticsStatusPackingShort: 'Packing',
    logisticsStatusConfirmedShort: 'Confirmed',
    logisticsDeliveredPrefix: 'Delivered ',
    logisticsEstimatedPrefix: 'Estimated delivery: ',
    logisticsSeeOrderDetails: 'See order details',
    logisticsNoShipmentsTitle: 'No active deliveries',
    logisticsNoShipmentsBody:
      'You currently have no active deliveries to track. When you place an order, it will appear here.',
    logisticsInfoFastTitle: 'Fast delivery',
    logisticsInfoFastBody:
      'We deliver your products within 3–5 business days with our trusted shipping partners.',
    logisticsInfoRealtimeTitle: 'Live tracking',
    logisticsInfoRealtimeBody:
      'Follow your delivery in real time with detailed tracking information and status updates.',
    logisticsInfoSupportTitle: 'Customer support',
    logisticsInfoSupportBody:
      'Our customer support team is available to help with any questions about your delivery.',
    logisticsPartnersTitle: 'Our delivery partners',
    logisticsPartnersMore: 'More partners',
    logisticsFaqTitle: 'Frequently asked questions',
    logisticsFaq1Q: 'How do I track my delivery?',
    logisticsFaq1A:
      'You can track your delivery from the "My orders" page, where you see all active shipments with tracking numbers and status.',
    logisticsFaq2Q: 'What if my parcel does not arrive?',
    logisticsFaq2A:
      'Contact us via the contact form if your delivery is more than 5 business days late. We will help you trace the parcel.',
    logisticsFaq3Q: 'Can I change the delivery address?',
    logisticsFaq3A:
      'Address changes are possible until the order has left our warehouse. Contact us as soon as possible for changes.',

    // Auth
    register: 'Register',
    email: 'Email address',
    password: 'Password',
    name: 'Full name',
    confirmPassword: 'Confirm password',
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Log in to your account to continue.',
    createAccount: 'Create your account',
    createAccountSubtitle: 'Start shopping today',
    fullName: 'Full name',
    yourEmail: 'your@email.com',
    minChars: 'At least 6 characters',
    passwordStrengthWeak: 'Weak',
    passwordStrengthMedium: 'Medium',
    passwordStrengthStrong: 'Strong',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: 'Don\'t have an account?',
    loginHere: 'Log in here',
    createAccountHere: 'Create an account here.',
    loggingIn: 'Logging in...',
    creatingAccount: 'Creating account...',
    createAccountBtn: 'Create account',
    passwordsMatch: 'Passwords match',
    passwordsDontMatch: 'Passwords don\'t match',
    fillAllFields: 'Please fill in all fields',
    wrongCredentials: 'Incorrect email or password',
    emailAlreadyExists: 'Email address is already registered',
    passwordTooShort: 'Password must be at least 6 characters',
    termsText: 'By registering you agree to our terms of use and privacy policy',
    
    // Footer - About Us
    aboutUs: 'About us',
    aboutCompany: 'About the company',
    career: 'Career',
    sustainability: 'Sustainability',
    press: 'Press',
    
    // Footer - Customer Service
    customerService: 'Customer service',
    contactUs: 'Contact us',
    shippingDelivery: 'Shipping & Delivery',
    returnsExchanges: 'Returns & Exchanges',
    faq: 'FAQ',
    sizeGuide: 'Size guide',
    
    // Footer - Terms
    terms: 'Terms',
    termsOfPurchase: 'Terms of purchase',
    privacyPolicy: 'Privacy policy',
    cookies: 'Cookies',
    rightOfWithdrawal: 'Right of withdrawal',
    
    // Footer - Other
    followUs: 'Follow us',
    allRightsReserved: 'All rights reserved.',
    paymentMethods: 'Payment methods',
    deliveryMethods: 'Delivery methods',
    
    // Reviews
    reviews: 'Reviews',
    writeReview: 'Write a review',
    reviewTitle: 'Title',
    reviewBody: 'Your review',
    reviewRating: 'Rating',
    submitReview: 'Submit review',
    noReviews: 'No reviews yet. Be the first to review!',
    verifiedPurchase: 'Verified purchase',
    
    // Delivery Info
    deliveryInfo: 'Delivery information',
    deliveryTime: 'Delivery time',
    deliveryTimeValue: '3-5 working days',
    freeShipping: 'Free shipping over $499',
    freeShippingInfo: 'Free shipping over $499',
    returnPolicy: 'Return policy',
    returnPolicyValue: '14 days right of withdrawal',
    
    // Breadcrumbs
    breadcrumbsHome: 'Home',
    breadcrumbsProducts: 'Products',
    
    // Misc
    ecommerce: 'E-commerce',
    companyName: 'Boxshe',
    
    // Categories
    categoryClothes: 'Clothes',
    categoryShoes: 'Shoes',
    categoryAccessories: 'Accessories',
    categoryJewelry: 'Jewelry',
    categoryElectronics: 'Electronics',
    categoryHomeDecor: 'Home & Decor',
    categorySportsFitness: 'Sports & Fitness',
    categoryBeauty: 'Beauty',
    categoryKids: 'Kids',
    categoryMen: 'Men',
    categoryWomen: 'Women',
    categoryAll: 'All',
    
    // Wishlist
    wishlist: 'Wishlist',
    yourSavedFavorites: 'Your saved favorite products',
    emptyWishlist: 'Your wishlist is empty',
    noSavedProducts: 'You haven\'t saved any products yet.',
    startShopping: 'Start shopping',
    
    // Contact Page
    contactPageTitle: 'Contact us',
    contactPageSubtitle: 'Do you have questions, feedback or need help? We are here for you and will respond as soon as possible.',
    contactInfo: 'Contact information',
    address: 'Address',
    phone: 'Phone',
    openingHours: 'Mon–Fri: 08:00–17:00',
    weRespondWithin24h: 'We respond within 24 hours',
    organizationNumber: 'Organization number',
    sendMessage: 'Send a message',
    yourName: 'Your name',
    subject: 'Subject',
    selectSubject: 'Select subject',
    orderQuestion: 'Order question',
    returnComplaint: 'Return and complaint',
    productQuestion: 'Product question',
    sustainabilityQuestion: 'Sustainability',
    other: 'Other',
    message: 'Message',
    writeMessageHere: 'Write your message here...',
    sendMessageBtn: 'Send message',
    commonQuestions: 'Frequently asked questions',
    howLongDelivery: 'How long is the delivery time?',
    deliveryAnswer: 'Standard delivery takes 3–5 working days. Express delivery is available at checkout.',
    whichPaymentMethods: 'Which payment methods do you accept?',
    paymentAnswer: 'We accept card payment (Visa, Mastercard) and Klarna installment payment.',
    howReturns: 'How do returns work?',
    returnsAnswer: 'You have 30 days right of withdrawal. Return shipping is free with our return label.',
    canChangeOrder: 'Can I change or cancel an order?',
    changeOrderAnswer: 'Contact customer service within 30 minutes after the order and we will help you.',
    deliverOutsideSweden: 'Do you deliver outside Sweden?',
    outsideSwedenAnswer: 'Yes, we deliver to all of the Nordic countries and EU. Shipping cost varies depending on destination.',
    
    // Terms of Purchase Page
    termsOfPurchaseTitle: 'Terms of Purchase',
    termsOfPurchaseIntro: 'Here you will find the general terms and conditions that apply when purchasing from our website.',
    lastUpdated: 'Last updated:',
    generalTerms: 'General Terms',
    generalTermsText: 'These general terms apply to all purchases made through our website. By ordering from us, you accept these terms. The terms together with your order confirmation constitute the agreement between you and us. We reserve the right to change these terms. For each order, the terms published on the website at the time of purchase apply. To shop with us, you must be at least 18 years old. We do not accept orders from minors without parental consent.',
    pricesAndPayment: 'Prices and Payment',
    pricesAndPaymentText: 'All prices are stated in USD and include VAT. When ordering from countries outside Sweden, additional customs duties and taxes may apply. We offer the following payment methods: card payment (Visa, Mastercard) and Klarna installment payment. Payment is made at the time of order. For installment payment via Klarna, Klarna\'s own terms apply, which you accept at the time of payment. We reserve the right to adjust prices on the website without prior notice. The applicable price is the one stated on the website at the time of purchase.',
    delivery: 'Delivery',
    deliveryText: 'Standard delivery takes 3–5 working days within Sweden. Express delivery with 1–2 working days is available as an option at checkout. Deliveries are made by PostNord, DHL or Budbee depending on the chosen delivery method and destination. For orders over $500, we offer free standard shipping within Sweden. For orders under $500, a shipping fee of $39 for standard shipping and $79 for express shipping applies. If an item is temporarily out of stock, we will inform you by email with an estimated delivery time. You then have the right to cancel the purchase if the delivery time does not suit you.',
    rightOfWithdrawalSection: 'Right of Withdrawal and Returns',
    rightOfWithdrawalText: 'According to the distance selling regulations, you have 14 days right of withdrawal from the date you receive the item. We offer an extended 30-day return policy. To exercise the right of withdrawal, the item must be unused and in the same condition as when you received it. All labels and packaging must be intact. Return shipping is always free. Contact our customer service to receive a return label. When exercising the right of withdrawal, the full purchase price will be refunded within 14 days from the date we receive the item. Exceptions to the right of withdrawal apply to items with broken packaging, custom-made products, and hygiene articles and underwear where the packaging has been broken.',
    complaints: 'Complaints',
    complaintsTermsText: 'According to consumer purchase law, you have the right to complain about an item within three years from the date of purchase, provided that the defect existed at the time of purchase. Complaints must be made within a reasonable time after you have discovered or should have discovered the defect. Complaints made within two months of discovery are always considered to have been made within a reasonable time. For approved complaints, we cover the return shipping. You have the right to choose between repair, replacement, price reduction, or refund. Contact our customer service to initiate a complaint. Include your order number and a description of the defect. We recommend that you take a photo of the defect to facilitate processing.',
    personalData: 'Personal Data',
    personalDataText: 'We process your personal data in accordance with GDPR and our privacy policy. You can find the full privacy policy under the Privacy Policy link at the bottom of the page. The personal data we collect is used to handle your order, delivery, and payment. The data is stored securely and shared only with our payment providers and logistics partners to the extent necessary to fulfill the agreement. You have the right to request access, correction, or deletion of your personal data. Contact our customer service for questions about personal data processing.',
    forceMajeure: 'Force Majeure',
    forceMajeureText: 'We are exempt from liability for failure to fulfill certain obligations under these terms if the failure is due to exempting circumstances as described below and the circumstances prevent, hinder, or delay performance. Exempting circumstances include, among other things, government action or omission, new or amended legislation, labor market conflict, blockade, fire, flooding, sabotage, major accidents, or other types of natural disasters. In case of force majeure, we have the right to terminate the agreement without obligation to pay damages.',
    disputes: 'Disputes',
    disputesText: 'We always strive to resolve any disputes with you in mutual agreement. If we nevertheless fail to reach an agreement, you can contact the General Complaints Board (ARN). You can also use the EU Commission\'s online dispute resolution platform (ODR), which is available at http://ec.europa.eu/odr. Any dispute shall first be resolved through negotiation. If the parties cannot agree, the dispute shall be decided by a Swedish court of general jurisdiction under Swedish law.',
    questionsAboutTerms: 'Do you have questions about our terms?',
    questionsAboutTermsText: 'Contact our customer service if anything is unclear or if you need help with an order.',
    
    // Privacy Policy Page
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyIntro: 'Your privacy is important to us. Here we describe how we collect, use and protect your personal data.',
    whoAreWe: 'Who are we?',
    whoAreWeText1: 'E-commerce AB (org.no 556123-4567) is the data controller for the processing of your personal data on this website.',
    whoAreWeText2: 'Our address is Storgatan 12, 111 22 Stockholm. You can reach our customer service at kundservice@example.se or phone +46 (0)8-123 45 67.',
    whatDataCollect: 'What data do we collect?',
    whatDataCollectText1: 'We collect the personal data that you provide to us when you place an order, contact customer service or sign up for our newsletter. This may include name, address, email address, phone number and payment information.',
    whatDataCollectText2: 'We also collect technical information about your device and your use of the website, such as IP address, browser type, operating system and visit statistics, via cookies and similar technologies.',
    whyProcessData: 'Why do we process your data?',
    whyProcessDataText1: 'We process your personal data to fulfill our agreement with you, i.e. handle your order, deliver goods and handle payments.',
    whyProcessDataText2: 'The data is also used for customer service, complaints and returns. With your consent, we may use the data for marketing and newsletters.',
    whyProcessDataText3: 'We analyze visit data to improve our website, customize our offering and prevent fraud.',
    legalBasis: 'Legal basis',
    legalBasisText1: 'The processing of your personal data is based on the following legal grounds according to GDPR:',
    legalBasisText2: 'Contract — to fulfill the purchase agreement with you.',
    legalBasisText3: 'Legal obligation — to fulfill accounting requirements and consumer rights laws.',
    legalBasisText4: 'Legitimate interest — to prevent fraud, ensure technical operation and analyze web traffic.',
    legalBasisText5: 'Consent — for marketing and newsletters. You can withdraw your consent at any time.',
    howLongStore: 'How long do we store the data?',
    howLongStoreText1: 'We only store your personal data for as long as necessary for the purposes stated in this policy.',
    howLongStoreText2: 'Order and payment information is stored in accordance with the Accounting Act (at least 7 years). Customer account information is stored as long as you have an active account. Marketing-related data is stored until you withdraw your consent.',
    whoShareWith: 'Who do we share data with?',
    whoShareWithText1: 'We only share your data with selected partners who help us run our business, and only to the extent required.',
    whoShareWithText2: 'This includes logistics partners (PostNord, DHL, DB Schenker) for delivery, payment providers (Klarna, Stripe) for transaction processing and IT providers for website operation.',
    whoShareWithText3: 'We never sell your personal data to third parties for marketing purposes.',
    yourRights: 'Your rights',
    yourRightsText1: 'According to GDPR, you have the following rights regarding your personal data:',
    yourRightsText2: 'Right to access — request an extract of what data we have about you.',
    yourRightsText3: 'Right to rectification — request that incorrect data be corrected.',
    yourRightsText4: 'Right to erasure — request that your data be deleted ("the right to be forgotten"), with certain exceptions according to law.',
    yourRightsText5: 'Right to restriction — request that the processing of your data be restricted.',
    yourRightsText6: 'Right to data portability — get your data in a structured format.',
    yourRightsText7: 'Right to object — object to processing based on legitimate interest or direct marketing.',
    contactAndComplaints: 'Contact and complaints',
    contactAndComplaintsText1: 'If you have questions about our personal data processing or want to exercise your rights, contact our customer service at kundservice@example.se.',
    contactAndComplaintsText2: 'If you believe that we have not handled your personal data correctly, you have the right to file a complaint with the Data Inspectorate (Privacy Protection Authority, IMY).',
    questionsAboutPrivacy: 'Do you have questions about our privacy policy?',
    questionsAboutPrivacyText: 'Contact our customer service if you have questions about how we handle your personal data.',
    contactCustomerService: 'Contact customer service',
    
    // Cookies Page
    cookiesTitle: 'Cookies',
    cookiesIntro: 'Information about how we use cookies and how you manage your settings',
    whatAreCookies: 'What are cookies?',
    whatAreCookiesText1: 'Cookies are small text files that are stored on your computer, tablet or mobile phone when you visit a website. They are used so that the website can recognize your device on return visits.',
    whatAreCookiesText2: 'Cookies are common on the internet and are an important part of how modern websites work. Without cookies, many functions such as login, shopping cart and language settings would not work properly.',
    howUseCookies: 'How do we use cookies?',
    howUseCookiesText: 'We use cookies to improve your experience on our website, analyze traffic and customize our content. Below we describe the different categories of cookies we use.',
    necessaryCookies: 'Necessary cookies',
    necessaryCookiesText1: 'These cookies are necessary for the website to function properly. They cannot be turned off in our systems and do not store any personally identifiable information.',
    necessaryCookiesText2: 'Examples: session cookies for the shopping cart, login status and security features.',
    functionalCookies: 'Functional cookies',
    functionalCookiesText1: 'Functional cookies enable the website to remember choices you make (e.g. language, region or currency) and provide enhanced, more personalized features.',
    functionalCookiesText2: 'Examples: language settings, saved login credentials and customized preferences.',
    analyticalCookies: 'Analytical cookies',
    analyticalCookiesText1: 'These cookies help us understand how visitors use our website by collecting and reporting information anonymously. The information is used to improve the website\'s structure and content.',
    analyticalCookiesText2: 'Examples: Google Analytics, visit statistics, page views and traffic sources.',
    marketingCookies: 'Marketing cookies',
    marketingCookiesText1: 'Marketing cookies are used to track visitors across websites. The intention is to display ads that are relevant and engaging to the individual user.',
    marketingCookiesText2: 'Examples: social media pixels, remarketing and advertising partners.',
    howManageCookies: 'How do you manage cookies?',
    howManageCookiesText1: 'You can change your cookie settings at any time by clicking the button below or by adjusting the settings in your browser.',
    howManageCookiesText2: 'Please note that disabling certain cookies may affect the functionality of our website and cause some services not to work as expected.',
    howManageCookiesText3: 'Most browsers allow you to control cookies through their settings. Information on how to do this can be found in your browser\'s help menu.',
    thirdPartyCookies: 'Third-party cookies',
    thirdPartyCookiesText1: 'Some cookies on our website are set by third parties, such as payment providers and analytics tools. These parties have their own privacy policies and we recommend that you read them.',
    thirdPartyCookiesText2: 'We currently use the following third-party services that may set cookies: Google Analytics (analytics), Klarna (installment payment) and Meta Pixel (marketing).',
    cookiesContact: 'Contact',
    cookiesContactText: 'If you have questions about our use of cookies, please contact our customer service at kundservice@example.se.',
    manageCookies: 'Manage your cookies',
    manageCookiesText: 'Update your cookie settings or contact us with questions',
    cookieSettings: 'Cookie settings',
    cookieBannerIntro: 'We use cookies to improve your experience.',
    cookieReadMore: 'Read more',
    cookieCustomize: 'Customize',
    cookieAccept: 'Accept',
    cookieSettingsSubtitle: 'Choose which cookies you want to allow',
    cookieRequiredBadge: '(Required)',
    cookieRejectAll: 'Reject all',
    cookieSave: 'Save',
    cookieAcceptAll: 'Accept all',
    shippingFreeOverShort: 'Free shipping on orders over 500 SEK',
    closeSearchAria: 'Close search',
    searchSuggestionsTitle: 'Search suggestions',
    recentSearchesTitle: 'Recent searches',
    clearRecentSearches: 'Clear',
    popularSearchesTitle: 'Popular searches',
    searchButtonLabel: 'Search',
    didYouMeanPrefix: 'Did you mean',
    swedishSecondary: 'Svenska',
    englishSecondary: 'Engelska',
    catalogTitleAll: 'All products',
    catalogTitleCategorySuffix: 'products',
    catalogCategoryLine: 'Showing {count} products in category "{cat}"',
    catalogAllLine: 'Showing {count} products from our assortment',
    catalogEmptyCategoryTitle: 'No products in this category',
    catalogEmptyGeneralTitle: 'No products available',
    catalogEmptyCategoryHint: 'We could not find any products in category "{cat}".',
    catalogEmptyDbBody: 'There seems to be a problem with the database connection.',
    catalogReturnToHome: 'Back to home',
    catalogFooterLine: 'Showing {shown} of {total} products',
    
    // Right of Withdrawal Page
    rightOfWithdrawalTitle: 'Right of Withdrawal',
    rightOfWithdrawalIntro: 'Your statutory right to cancel a distance purchase within 14 days. We offer an extended 30-day return policy.',
    yourRightOfWithdrawal: 'Your right of withdrawal',
    yourRightOfWithdrawalText1: 'According to the Distance Selling Act (2005:59), you have the right to withdraw from a distance contract within 14 calendar days from the date you received the goods.',
    yourRightOfWithdrawalText2: 'We offer an extended return policy and give you 30 days to decide if you want to keep your item. The withdrawal period starts from the day you received the goods.',
    yourRightOfWithdrawalText3: 'The right of withdrawal applies provided that the goods are returned in essentially unchanged condition. The goods may be tried on, but must not have been used or damaged.',
    howToWithdraw: 'How to cancel a purchase',
    howToWithdrawText1: 'Contact our customer service at kundservice@example.se or use the form below.',
    howToWithdrawText2: 'State your order number and which items you want to return.',
    howToWithdrawText3: 'We will send you a free return label.',
    howToWithdrawText4: 'Pack the item in the original packaging with all labels and accessories.',
    howToWithdrawText5: 'Drop off the package according to the instructions on the return label.',
    refund: 'Refund',
    refundText1: 'We will refund all payments we have received from you, including delivery costs, no later than 14 days from the date we received your notice of withdrawal.',
    refundText2: 'We will wait with the refund until we have received the goods back or you have provided us with proof that the goods have been returned.',
    refundText3: 'The refund will be made via the same payment method used for the purchase.',
    exceptionsFromWithdrawal: 'Exceptions from the right of withdrawal',
    exceptionsFromWithdrawalText: 'The right of withdrawal does not apply to the following goods according to law:',
    exceptionsFromWithdrawalText1: 'Goods manufactured according to your specifications or have a clear personal character.',
    exceptionsFromWithdrawalText2: 'Goods that due to their nature can be destroyed or become outdated quickly.',
    exceptionsFromWithdrawalText3: 'Sealed goods that for health or hygiene reasons are not suitable for return if the seal has been broken.',
    exceptionsFromWithdrawalText4: 'Audio and video recordings or software in sealed packaging if the seal has been broken.',
    exceptionsFromWithdrawalText5: 'Newspapers, magazines or periodicals with the exception of subscription agreements.',
    needHelpWithReturn: 'Need help with your return?',
    needHelpWithReturnText: 'Our customer service helps you with all questions about the right of withdrawal and returns.',
    
    // About Us Page
    aboutUsTitle: 'About us',
    aboutUsSubtitle: 'We started Boxshe to make it easy to find good products at a fair price – with service that actually works.',
    customerSatisfaction: 'Customer satisfaction',
    yearsInBusiness: 'Years in business',
    employees: 'Employees',
    customers: 'Customers',
    customersCount: 'Customers',
    productsCount: 'Products',
    ourMission: 'What we do',
    ourMissionText: 'We select products we would buy ourselves and make sure they reach you quickly and in good condition. It really is that simple.',
    handpickedProducts: 'Carefully selected products',
    fastSecureDeliveries: 'Reliable deliveries',
    personalCustomerService: 'Customer service that actually helps',
    ourCoreValues: 'What we believe in',
    quality: 'Quality',
    qualityDesc: 'We only sell products we are happy with ourselves. If something does not meet the standard, we take it back.',
    trust: 'Honesty',
    trustDesc: 'We are clear about what applies – prices, delivery times and return conditions without any fuss.',
    innovation: 'Simplicity',
    innovationDesc: 'Shopping online should be straightforward. We are always working to remove unnecessary steps.',
    ourJourney: 'Our story',
    ourJourneyText1: 'Boxshe was founded in 2009 by a group of people who were tired of online shopping being either expensive, unreliable, or both. We wanted to show that it was possible to do better – with a focused and well-chosen range, honest prices and customer service that genuinely helps.',
    ourJourneyText2: 'Since then we have grown steadily. Today we have customers across the Nordics and a team of over 50 people working hard to make every order feel right. We are still a family business and that shows in how we work.',
    keyMilestones: 'Milestones',
    founding: 'Founded',
    foundingDesc: 'Boxshe opens with a small but carefully selected range.',
    expansion: 'Expansion',
    expansionDesc: 'Our own warehouse in Stockholm and deliveries across Sweden.',
    digitalTransformation: 'New platform',
    digitalTransformationDesc: 'New website and improved order management.',
    internationalExpansion: 'The Nordics',
    internationalExpansionDesc: 'Deliveries to Norway, Denmark, Finland and Iceland.',
    meetOurTeam: 'Meet our team',
    ceo: 'CEO',
    ceoDesc: '15+ years of experience in e-commerce and digital transformation',
    cto: 'CTO',
    ctoDesc: 'Expert in scalable e-commerce platforms and system architecture',
    cmo: 'CMO',
    cmoDesc: 'Specialist in digital marketing and customer experiences',
    ourVisionForFuture: 'Looking ahead',
    visionText: 'We are aiming to keep growing in the Nordics and bring in more product categories. But we will not grow faster than we can maintain quality.',
    sustainabilityVision: 'Sustainability',
    sustainabilityVisionDesc: 'Environmentally conscious deliveries and sustainable products',
    growth: 'Growth',
    growthDesc: 'Expand into new markets and customer segments',
    community: 'Community',
    communityDesc: 'Build strong relationships with customers and partners',
    certificationsAwards: 'Certifications & Awards',
    swedishEcommerce: 'Swedish E-commerce',
    swedishEcommerceDesc: 'Certified member of Swedish Digital Commerce',
    iso9001: 'ISO 9001',
    iso9001Desc: 'Quality certification for management systems',
    gazelle: 'Gazelle',
    gazelleDesc: 'Named Gazelle company 2023',
    partnerships: 'Partnerships',
    environmentalCommitment: 'Environmental Commitment',
    environmentalCommitmentDesc: 'Climate-neutral deliveries and 100% renewable energy in our warehouses',
    localEngagementDesc: 'Collaboration with local organisations and support for young entrepreneurs',
    charityDesc: '1% of our revenue goes to charitable organisations working with the environment and education.',
    educationDesc: 'Support for education projects in our production countries for equality and hope for the future.',
    sustainabilityCommitment: 'Sustainable packaging',
    sustainabilityCommitmentDesc: 'All our packaging is recyclable and we use minimal filling material.',
    technologyInnovation: 'Technology & Innovation',
    modernTechnology: 'Modern Technology',
    modernTechnologyDesc: 'Advanced technology for personalisation and optimisation',
    cloudNative: 'Cloud Native',
    cloudNativeDesc: 'Built on modern cloud infrastructure for scalability',
    fastDeliveries: 'Fast Deliveries',
    fastDeliveriesDesc: 'Automated processes for fast order handling',

    // Sustainability Page
    sustainabilityPageTitle: 'Sustainability',
    sustainabilityPageSubtitle: 'We take responsibility for our impact – on the environment, on people and throughout the supply chain.',
    sustainabilityPromise: 'Our sustainability promise',
    sustainabilityMilestones: 'Our sustainability milestones',
    environmentalGoals2025: 'Environmental goals for 2025',
    miljoIBilder: 'Environment in pictures',
    miljoIBilderDesc: 'Seven images that reflect what we work towards',
    ethicalProductionDesc:
      'We only work with suppliers who meet high standards for working conditions and human rights.',
    climateNeutralCert: 'Climate Neutral',
    climateNeutralCertDesc: 'Climate-neutral certification for our entire operation',
    makeADifference: 'Make a difference together',
    makeADifferenceText:
      'Every purchase you make from us contributes to a more sustainable future. Together we can create real change — for the planet, for people and for future generations.',
    exploreSustainableProducts: 'Explore our sustainable products',
    ourSustainabilityPromiseTitle: 'Our Sustainability Promise',
    sustainabilityPromise1: 'Climate-neutral deliveries through climate compensation',
    sustainabilityPromise2: 'Circular economy and recycling throughout the chain',
    sustainabilityPromise3: 'Ethical production with respect for human rights',
    environmentInPictures: 'Environment in Pictures',
    environmentInPicturesDesc: 'Seven environment-based images that reflect our values',
    solarEnergy: 'Solar Energy & Renewable Energy',
    recycling: 'Recycling & Circular Economy',
    organicFarming: 'Organic Farming & Cotton',
    sustainableTransport: 'Sustainable Transport System',
    rainforest: 'Rainforest & Climate Compensation',
    cleanWater: 'Clean Water & Water Care',
    localCommunity: 'Local Community & Fair Trade',
    ourCoreValuesTitle: 'Our Core Values',
    environmentalResponsibility: 'Environmental Responsibility',
    environmentalResponsibilityDesc: 'Protect and restore our natural resources through conscious choices at every stage.',
    transparency: 'Transparency',
    transparencyDesc: 'We are open about our impact and progress, with annual sustainability reports.',
    innovationSustainability: 'Innovation',
    innovationSustainabilityDesc: 'Constantly seeking new sustainable solutions for materials, processes and logistics.',
    ourMainInitiatives: 'Our main initiatives',
    climateNeutralDeliveriesTitle: 'Climate-neutral Deliveries',
    climateNeutralDeliveriesText: 'All our deliveries are climate-neutral through climate compensation and choice of environmentally friendly transport alternatives.',
    circularEconomyTitle: 'Circular Economy',
    circularEconomyText: 'We recycle and reuse materials throughout our chain, from production to packaging.',
    ethicalProduction: 'Ethical Production',
    ethicalProductionText: 'We only work with suppliers who meet high standards for working conditions and human rights.',
    ourEnvironmentalGoals2025: 'Environmental goals for 2025',
    goal1: '100% recycled materials in all products',
    goal2: 'Zero carbon emissions from our operations',
    goal3: 'All packaging 100% recyclable',
    goal4: 'Fair Trade certification for all products',
    goal5: '100% renewable energy in all our facilities',
    goal6: 'Zero water waste in production',
    responsibilityInChainTitle: 'Responsibility in the Entire Chain',
    responsibilityInChainText2: 'From raw materials to finished product — we take responsibility for every step in our supply chain. Our products are manufactured under fair conditions with respect for both people and the environment.',
    socialResponsibility: 'Social Responsibility',
    socialResponsibilityTitle: 'Social Responsibility',
    charity: 'Charity',
    charityTitle: 'Charity',
    charityText: '1% of our revenue goes to charitable organisations working with the environment and education.',
    charityDesc: '1% of our revenue goes to charitable organisations working with the environment and education.',
    education: 'Education',
    educationText: 'Support for education projects in our production countries for equality and hope for the future.',
    localEngagement: 'Local Engagement',
    localEngagementTitle: 'Local Engagement',
    localEngagementText: 'Collaboration with local organisations and projects in communities where we operate.',
    localEngagementDesc: 'Collaboration with local organisations and support for young entrepreneurs',
    ourSustainabilityMilestones: 'Our sustainability milestones',
    milestone2020: 'All our deliveries became climate-neutral through climate compensation',
    milestone2021: 'Our facilities and warehouses are powered entirely by renewable energy',
    milestone2023: '50% of our products are now Fair Trade certified',
    milestone2025: 'Our goal: zero carbon emissions throughout our operations',
    certificationsAwardsTitle: 'Certifications & Awards',
    fairTrade: 'Fair Trade',
    fairTradeDesc: 'Certified for fair trade',
    bCorp: 'B Corp',
    bCorpDesc: 'Certified for social and environmental performance',
    climateNeutral: 'Climate Neutral',
    climateNeutralDesc: 'Climate-neutral certification for the entire operation',
    makeDifferenceTogether: 'Make a difference together',
    makeDifferenceText: 'Every purchase you make from us contributes to a more sustainable future. Together we can create real change — for the planet, for people and for future generations.',
    exploreProducts: 'Explore our sustainable products',

    recyclingCircular: 'Recycling & Circular Economy',
    rainforestCompensation: 'Rainforest & Climate Compensation',
    localCommunityFairTrade: 'Local Community & Fair Trade',

    popularProductsTitle: 'Popular products',
    popularProductsSubtitle: 'Curated styles from our current assortment.',
    productImagePlaceholder: 'Product image',
    featuredViewAllProducts: 'See all products',
    shopByCategoryTitle: 'Shop by category',
    shopByCategorySubtitle: 'Explore our popular categories and find exactly what you are looking for',
    categoryProductCount: 'products',
    comingSoonLabel: 'Coming soon',
    catIconSweater: 'Sweater',
    catIconMen: 'Men',
    catIconWomen: 'Women',
    catIconTrousers: 'Trousers',
    catIconDress: 'Dress',
    catIconJacket: 'Jacket',
    catIconTshirt: 'T-shirt',
    heroBannerFreeShipping: 'Free shipping – T&Cs apply',
    heroBannerFreeReturns: 'Free returns',
    heroBannerNoHiddenFees: 'No hidden fees',
    heroCatSuperDeals: 'Super Deals',
    heroCatTopTrends: 'Top Trends',
    heroCatBrandZone: 'Brand Zone',
    heroCatFlashSale: 'Flash Sale',
    heroCatNewIn: 'New In',
    heroLoadMore: 'Load more',
    heroLoading: 'Loading...',
    heroSeenAllInCategory: 'You have seen all products in the "{category}" category',
    heroExploreOtherCategories: 'Explore other categories →',
    heroAddToCartAria: 'Add to cart',
    heroWishlistAria: 'Add to wishlist',
    gridRefreshingProducts: 'Refreshing products...',
    gridLoading: 'Loading...',
    gridLoadMore: 'Load more',
    faqPageTitle: 'Frequently asked questions',
    faqPageSubtitle: 'Find quick answers to your questions. Use search or filter by topic below.',
    faqSearchPlaceholder: 'Search questions and answers...',
    faqNoResults: 'No questions found',
    faqNoResultsHint: 'Try another search or category',
    faqContactTitle: 'Can\'t find the answer?',
    faqContactSubtitle: 'Our customer service is available Monday–Friday and usually responds within 24 hours.',
    faqContactButton: 'Contact customer service',
    faqCatAll: 'All',
    faqCatDelivery: 'Delivery',
    faqCatPayment: 'Payment',
    faqCatReturns: 'Returns',
    faqCatProducts: 'Products',
    faqCatCustomerService: 'Customer service',

    // Shipping & Delivery Page
    shippingAndDelivery: 'Shipping & Delivery',
    shippingSubtitle: 'We offer global deliveries. Standard shipping 2-4 business days, express 1-2 business days.',
    deliveryOptions: 'Delivery Options',
    standardShipping: 'Standard Shipping',
    standardShippingTime: '2-4 business days',
    standardShippingDesc: 'Global delivery • Free shipping over $500',
    expressShipping: 'Express Shipping',
    expressShippingTime: '1-2 business days',
    expressShippingDesc: 'Global delivery • Door-to-door delivery',
    deliveryAreas: 'Delivery Areas',
    sweden: 'Sweden',
    swedenDesc: 'Delivery to the entire country',
    nordics: 'Nordics',
    nordicsDesc: 'Norway, Denmark, Finland, Iceland',
    eu: 'EU',
    euDesc: 'All EU countries',
    restOfWorld: 'Rest of the World',
    restOfWorldDesc: 'Global delivery',
    trackYourDelivery: 'Track Your Delivery',
    trackYourDeliveryText: 'When your order has been shipped, you will receive an email with a tracking number. You can use this number to follow your shipment on the carrier\'s website.',
    transportMethods: 'Transport Methods:',
    postnordDesc: 'PostNord – Global deliveries',
    dhlDesc: 'DHL – International shipping',
    schenkerDesc: 'DB Schenker – Logistics solutions',
    deliveryTimes: 'Delivery Times',
    region: 'Region',
    deliveryTimeTable: 'Delivery Time',
    shippingPrice: 'Shipping Price',
    questionsAboutDelivery: 'Questions about delivery?',
    questionsAboutDeliveryText: 'Contact our customer service and we will help you with tracking, delivery status or other questions.',

    // Returns & Exchanges Page
    returnsAndExchanges: 'Returns & Exchanges',
    returnsSubtitle: 'We want you to be satisfied with your purchase. Here you will find all the information on how to return or exchange an item.',
    howToReturn: 'How to return',
    registerReturn: '1. Register return',
    registerReturnDesc: 'Log in to your account and register your return digitally.',
    packItem: '2. Pack the item',
    packItemDesc: 'Pack the item in the original packaging with all labels remaining.',
    sendBack: '3. Send back',
    sendBackDesc: 'Use the included return label and drop off the package.',
    returnConditions: 'Return Conditions',
    thirtyDaysReturn: '30 days money back guarantee',
    thirtyDaysReturnDesc: 'You always have a 30-day return policy from the time you received your order.',
    freeReturnShipping: 'Free return shipping',
    freeReturnShippingDesc: 'We send a return label at no extra cost for all returns.',
    unusedItems: 'Unused items',
    unusedItemsDesc: 'The item must be unused and in original condition with all labels remaining.',
    refundCondition: 'Refund',
    refundDesc: 'Refund is made within 5 business days after we have received your return.',
    exchanges: 'Exchanges',
    exchangesText: 'Do you want to change to another size or color? Contact our customer service and we will help you with your exchange. Exchanges are free within 30 days of receipt.',
    exchangeSize: 'Exchange to another size',
    exchangeSizeDesc: 'Send back the item and state the desired size upon return. We will send the new size as soon as we have received your return.',
    exchangeColor: 'Exchange to another color',
    exchangeColorDesc: 'If the color does not match expectations, you can easily change to another color within 30 days.',
    complaintsTitle: 'Complaints',
    complaintsText: 'Have you received a defective or incorrect item? We apologize for the inconvenience and will of course help you solve it as quickly as possible.',
    whenComplaining: 'When complaining:',
    complaintStep1: 'Contact customer service with order number and picture of the fault',
    complaintStep2: 'We send a free return label for the complaint',
    complaintStep3: 'You can choose between a new item or a full refund',
    questionsAboutReturns: 'Questions about returns?',
    questionsAboutReturnsText: 'Contact our customer service and we will help you with your return, exchange or complaint.',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('sv')
  const [isClient, setIsClient] = useState(false)

  // Set isClient flag on mount
  useEffect(() => {
    setIsClient(true)
  }, [])

  // Load language from localStorage on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language | null
      if (savedLanguage && (savedLanguage === 'sv' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage)
      }
    }
  }, [])

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  // Sync <html lang> with selected language (a11y + browser behavior)
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'sv' ? 'sv' : 'en'
    }
  }, [language])

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const dict = translations[language] as Record<string, string>
    let s = dict[key] ?? key
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        s = s.split(`{${k}}`).join(String(v))
      }
    }
    return s
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
