'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'sv' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  sv: {
    search: 'Sök produkter...',
    login: 'Logga in',
    logout: 'Logga ut',
    hello: 'Hej',
    cart: 'Varukorg',
    products: 'Våra Produkter',
    addToCart: 'Kundvagn',
    outOfStock: 'Slutsåld',
    total: 'Totalt',
    checkout: 'Gå till kassan',
    emptyCart: 'Din varukorg är tom',
    register: 'Registrera',
    email: 'E-postadress',
    password: 'Lösenord',
    name: 'Fullständigt namn',
    confirmPassword: 'Bekräfta lösenord',
    continueShoppingBtn: 'Fortsätt handla',
    removeBtn: 'Ta bort',
    clearCartBtn: 'Töm varukorg',
    image: 'Bild',
    welcomeBack: 'Välkommen tillbaka',
    loginSubtitle: 'Logga in på ditt konto för att fortsätta.',
    createAccount: 'Skapa ditt konto',
    createAccountSubtitle: 'Börja handla idag',
    fullName: 'Fullständigt namn',
    yourName: 'Ditt namn',
    yourEmail: 'din@email.com',
    minChars: 'Minst 6 tecken',
    passwordStrengthWeak: 'Svagt',
    passwordStrengthMedium: 'Medel',
    passwordStrengthStrong: 'Starkt',
    alreadyHaveAccount: 'Har du redan ett konto?',
    noAccount: 'Har du inget konto?',
    loginHere: 'Logga in här',
    createAccountHere: 'Skapa ett konto här.',
    loggingIn: 'Loggar in...',
    creatingAccount: 'Skapar konto...',
    createAccountBtn: 'Skapa konto',
    passwordsMatch: 'Lösenorden matchar',
    passwordsDontMatch: 'Lösenorden matchar inte',
    fillAllFields: 'Vänligen fyll i alla fält',
    wrongCredentials: 'Felaktig e-post eller lösenord',
    emailAlreadyExists: 'E-postadressen är redan registrerad',
    passwordTooShort: 'Lösenordet måste vara minst 6 tecken',
    termsText: 'Genom att registrera dig godkänner du våra användarvillkor och integritetspolicy',
    // New translations for hardcoded texts
    menu: 'Meny',
    categories: 'Kategorier',
    deliveryDay: '24 arbetsdagar',
    aboutUs: 'Om oss',
    aboutCompany: 'Om företaget',
    career: 'Karriär',
    sustainability: 'Hållbarhet',
    press: 'Press',
    customerService: 'Kundservice',
    contactUs: 'Kontakta oss',
    shippingDelivery: 'Frakt & Leverans',
    returnsExchanges: 'Returer & Byten',
    faq: 'Vanliga frågor',
    sizeGuide: 'Storleksguide',
    terms: 'Villkor',
    termsOfPurchase: 'Köpvillkor',
    privacyPolicy: 'Integritetspolicy',
    cookies: 'Cookies',
    rightOfWithdrawal: 'Ångerrätt',
    followUs: 'Följ oss',
    paymentMethods: 'Betalmetoder',
    allRightsReserved: 'Alla rättigheter förbehållna.',
    ecommerce: 'E-handel',
    imageSearch: 'Bildsök',
    // Product page
    productDetails: 'Produktdetaljer',
    specifications: 'Specifikationer',
    description: 'Beskrivning',
    price: 'Pris',
    category: 'Kategori',
    availability: 'Tillgänglighet',
    inStock: 'I lager',
    outOfStockBadge: 'Slut i lager',
    quantity: 'Antal',
    addToCartBtn: 'Lägg i varukorg',
    reviews: 'Recensioner',
    writeReview: 'Skriv en recension',
    reviewTitle: 'Rubrik',
    reviewBody: 'Din recension',
    reviewRating: 'Betyg',
    submitReview: 'Skicka recension',
    noReviews: 'Inga recensioner ännu. Bli den första att recensera!',
    verifiedPurchase: 'Verifierat köp',
    deliveryInfo: 'Leveransinformation',
    deliveryTime: 'Leveranstid',
    deliveryTimeValue: '3-5 arbetsdagar',
    freeShipping: 'Fri frakt över $499',
    returnPolicy: 'Returpolicy',
    returnPolicyValue: '14 dagars ångerrätt',
    securePayment: 'Säker betalning',
    securePaymentValue: 'Krypterad betalning',
    breadcrumbsHome: 'Hem',
    breadcrumbsProducts: 'Produkter',
    relatedProducts: 'Liknande produkter',
    colors: 'Färger',
  },
  en: {
    search: 'Search products...',
    login: 'Log in',
    logout: 'Log out',
    hello: 'Hello',
    cart: 'Shopping cart',
    products: 'Our Products',
    addToCart: 'Add to cart',
    outOfStock: 'Out of stock',
    total: 'Total',
    checkout: 'Checkout',
    emptyCart: 'Your shopping cart is empty',
    register: 'Register',
    email: 'Email address',
    password: 'Password',
    name: 'Full name',
    confirmPassword: 'Confirm password',
    continueShoppingBtn: 'Continue shopping',
    removeBtn: 'Remove',
    clearCartBtn: 'Clear cart',
    image: 'Image',
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Log in to your account to continue.',
    createAccount: 'Create your account',
    createAccountSubtitle: 'Start shopping today',
    fullName: 'Full name',
    yourName: 'Your name',
    yourEmail: 'your@email.com',
    minChars: 'At least 6 characters',
    passwordStrengthWeak: 'Weak',
    passwordStrengthMedium: 'Medium',
    passwordStrengthStrong: 'Strong',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: 'Don\'t have an account?',
    loginHere: 'Log in here',
    createAccountHere: 'Create an account here.',
    loggingIn: 'Logging in...',
    creatingAccount: 'Creating account...',
    createAccountBtn: 'Create account',
    passwordsMatch: 'Passwords match',
    passwordsDontMatch: 'Passwords don\'t match',
    fillAllFields: 'Please fill in all fields',
    wrongCredentials: 'Incorrect email or password',
    emailAlreadyExists: 'Email address is already registered',
    passwordTooShort: 'Password must be at least 6 characters',
    termsText: 'By registering you agree to our terms of use and privacy policy',
    // New translations for hardcoded texts
    menu: 'Menu',
    categories: 'Categories',
    deliveryDay: '24 working days',
    aboutUs: 'About us',
    aboutCompany: 'About the company',
    career: 'Career',
    sustainability: 'Sustainability',
    press: 'Press',
    customerService: 'Customer service',
    contactUs: 'Contact us',
    shippingDelivery: 'Shipping & Delivery',
    returnsExchanges: 'Returns & Exchanges',
    faq: 'FAQ',
    sizeGuide: 'Size guide',
    terms: 'Terms',
    termsOfPurchase: 'Terms of purchase',
    privacyPolicy: 'Privacy policy',
    cookies: 'Cookies',
    rightOfWithdrawal: 'Right of withdrawal',
    followUs: 'Follow us',
    paymentMethods: 'Payment methods',
    allRightsReserved: 'All rights reserved.',
    ecommerce: 'E-commerce',
    imageSearch: 'Image search',
    // Product page
    productDetails: 'Product details',
    specifications: 'Specifications',
    description: 'Description',
    price: 'Price',
    category: 'Category',
    availability: 'Availability',
    inStock: 'In stock',
    outOfStockBadge: 'Out of stock',
    quantity: 'Quantity',
    addToCartBtn: 'Add to cart',
    reviews: 'Reviews',
    writeReview: 'Write a review',
    reviewTitle: 'Title',
    reviewBody: 'Your review',
    reviewRating: 'Rating',
    submitReview: 'Submit review',
    noReviews: 'No reviews yet. Be the first to review!',
    verifiedPurchase: 'Verified purchase',
    deliveryInfo: 'Delivery information',
    deliveryTime: 'Delivery time',
    deliveryTimeValue: '3-5 working days',
    freeShipping: 'Free shipping over $499',
    returnPolicy: 'Return policy',
    returnPolicyValue: '14 days right of withdrawal',
    securePayment: 'Secure payment',
    securePaymentValue: 'Encrypted payment',
    breadcrumbsHome: 'Home',
    breadcrumbsProducts: 'Products',
    relatedProducts: 'Related products',
    colors: 'Colors',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('sv')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.sv] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
